import {Language, LangCopy } from '../constants';

export type AboutCopy = {
  eyebrow: string;
  title: string;
  lead: string;
  intro: string;
  block1Title: string;
  block1Text1: string;
  block1Text2: string;
  block2Title: string;
  block2Text1: string;
  block2Text2: string;
  finalTitle: string;
  finalText1: string;
  finalText2: string;
  finalText3: string;
};

export const ABOUT_COPY: LangCopy< AboutCopy> = {
  en: {
    eyebrow: 'About',
    title: 'About Luna29',
    lead: 'Luna29 was born inside a much larger research environment.',
    intro: 'For many years our team has been working on a long-term project called BioMath — a digital modeling initiative focused on understanding how the human body changes over time. The work behind BioMath explores physiological rhythms, biological signals, behavioral patterns, and the complex ways they interact to shape energy, mood, and recovery.',
    block1Title: 'From BioMath To Luna29',
    block1Text1: 'Within this broader system, more than 200 different services and tools are being developed to help people better observe and understand their own biological dynamics.',
    block1Text2: 'Luna29 is one of those services. During the development of BioMath we realized that one part of this work — helping women calmly observe their internal rhythms and translate those signals into clear understanding — could stand on its own. The result is Luna29.',
    block2Title: 'What Luna29 Focuses On',
    block2Text1: 'Luna29 focuses on a simple but often overlooked need: the ability to pause, observe internal signals, and form a clear picture of what is happening inside the body and mind at a given moment.',
    block2Text2: 'Behind Luna29 are years of work in digital modeling, data structures for human physiology, and the study of long-term biological patterns. These efforts were not originally intended to create a single application.',
    finalTitle: 'A Distilled Practical Layer',
    finalText1: 'Luna29 represents a distilled, practical part of that work.',
    finalText2: 'It does not attempt to diagnose or treat. Instead, it offers a quiet digital environment where physiological rhythms, personal observations, and reflection can come together to create a deeper sense of clarity.',
    finalText3: 'In the broader BioMath ecosystem, Luna29 is one piece of a much larger vision. On its own, it is a simple tool designed to bring that deeper research into everyday life in a calm and accessible way.',
  },
  ru: {
    eyebrow: 'О проекте',
    title: 'О Luna29',
    lead: 'Luna29 родилась внутри гораздо более широкой исследовательской среды.',
    intro: 'На протяжении многих лет наша команда работает над долгосрочным проектом BioMath — инициативой цифрового моделирования, направленной на понимание того, как человеческое тело меняется во времени. Работа в BioMath исследует физиологические ритмы, биологические сигналы, поведенческие паттерны и сложные связи между ними, влияющие на энергию, настроение и восстановление.',
    block1Title: 'От BioMath к Luna29',
    block1Text1: 'Внутри этой широкой системы разрабатывается более 200 сервисов и инструментов, которые помогают людям лучше наблюдать и понимать собственную биологическую динамику.',
    block1Text2: 'Luna29 — один из таких сервисов. В процессе разработки BioMath мы поняли, что отдельная часть этой работы — спокойное наблюдение внутренних ритмов у женщин и перевод этих сигналов в ясное понимание — может существовать как самостоятельный инструмент. Так появилась Luna29.',
    block2Title: 'На чем фокусируется Luna29',
    block2Text1: 'Luna29 сосредоточена на простой, но часто недооцененной потребности: умении остановиться, заметить внутренние сигналы и сформировать ясную картину того, что происходит в теле и сознании в конкретный момент.',
    block2Text2: 'За Luna29 стоят годы работы в цифровом моделировании, структуры данных человеческой физиологии и исследования долгосрочных биологических паттернов. Изначально эти усилия не были направлены на создание одного приложения.',
    finalTitle: 'Сжатый практический слой',
    finalText1: 'Luna29 — это концентрированная практическая часть этой большой работы.',
    finalText2: 'Она не пытается ставить диагнозы или лечить. Вместо этого Luna29 дает тихую цифровую среду, где физиологические ритмы, личные наблюдения и рефлексия соединяются в более ясное понимание состояния.',
    finalText3: 'В экосистеме BioMath Luna29 — лишь часть гораздо более широкой визии. Но сама по себе это простой инструмент, который делает глубокие исследования доступными в повседневной жизни — спокойно и понятно.',
  },
  uk: {
    eyebrow: 'Про проект',
    title: 'Про Luna29',
    lead: 'Luna29 народилася всередині значно ширшого дослідницького середовища.',
    intro: 'Протягом багатьох років наша команда працює над довгостроковим проєктом BioMath — ініціативою цифрового моделювання, що вивчає, як людське тіло змінюється з часом. Робота BioMath досліджує фізіологічні ритми, біологічні сигнали, поведінкові патерни та їхні складні взаємозвʼязки, які формують енергію, настрій і відновлення.',
    block1Title: 'Від BioMath до Luna29',
    block1Text1: 'У межах цієї ширшої системи розробляється понад 200 сервісів та інструментів, що допомагають людям краще спостерігати й розуміти власну біологічну динаміку.',
    block1Text2: 'Luna29 — один із цих сервісів. Під час розвитку BioMath ми побачили, що окрема частина цієї роботи — допомога жінкам спокійно спостерігати внутрішні ритми та перетворювати сигнали на ясне розуміння — може існувати самостійно.',
    block2Title: 'Фокус Luna29',
    block2Text1: 'Luna29 зосереджена на простій, але часто недооціненій потребі: зупинитися, помітити внутрішні сигнали та сформувати чітку картину того, що відбувається в тілі й свідомості саме зараз.',
    block2Text2: 'За Luna29 стоять роки праці в цифровому моделюванні, структурах даних людської фізіології та вивченні довгострокових біологічних патернів.',
    finalTitle: 'Практичне втілення великої роботи',
    finalText1: 'Luna29 — це концентрована практична частина цього великого напрямку.',
    finalText2: 'Вона не діагностує і не лікує. Натомість Luna29 надає тихий цифровий простір, де фізіологічні ритми, особисті спостереження й рефлексія поєднуються у ясність.',
    finalText3: 'У ширшій екосистемі BioMath Luna29 — лише одна частина великого бачення. Але окремо це простий інструмент, що переносить глибокі дослідження в повсякденне життя спокійно й доступно.',
  },
  es: {
    eyebrow: 'Acerca',
    title: 'Sobre Luna29',
    lead: 'Luna29 nació dentro de un entorno de investigación mucho más amplio.',
    intro: 'Durante muchos años nuestro equipo ha trabajado en un proyecto de largo plazo llamado BioMath — una iniciativa de modelado digital enfocada en comprender cómo cambia el cuerpo humano con el tiempo. BioMath explora ritmos fisiológicos, señales biológicas, patrones de comportamiento y sus interacciones complejas.',
    block1Title: 'De BioMath a Luna29',
    block1Text1: 'Dentro de este sistema más amplio se están desarrollando más de 200 servicios y herramientas para ayudar a las personas a observar y comprender mejor su dinámica biológica.',
    block1Text2: 'Luna29 es uno de esos servicios. En el desarrollo de BioMath entendimos que una parte de ese trabajo — ayudar a las mujeres a observar sus ritmos internos con calma y traducir esas señales en comprensión clara — podía funcionar por sí sola.',
    block2Title: 'En qué se enfoca Luna29',
    block2Text1: 'Luna29 se centra en una necesidad simple pero olvidada: pausar, observar señales internas y formar una imagen clara de lo que sucede en cuerpo y mente.',
    block2Text2: 'Detrás de Luna29 hay años de modelado digital, estructuras de datos fisiológicos y estudio de patrones biológicos de largo plazo.',
    finalTitle: 'Una capa práctica condensada',
    finalText1: 'Luna29 representa una parte práctica y destilada de ese trabajo.',
    finalText2: 'No intenta diagnosticar ni tratar. Ofrece un entorno digital tranquilo donde ritmos fisiológicos, observaciones personales y reflexión se unen para generar claridad.',
    finalText3: 'En el ecosistema BioMath, Luna29 es una pieza de una visión mucho mayor. Por sí sola, es una herramienta simple que acerca esa investigación a la vida cotidiana.',
  },
  fr: {
    eyebrow: 'A Propos',
    title: 'A propos de Luna29',
    lead: 'Luna29 est nee au sein d un environnement de recherche beaucoup plus vaste.',
    intro: 'Depuis des annees, notre equipe travaille sur BioMath, une initiative de modelisation numerique consacree a la comprehension des evolutions du corps humain dans le temps.',
    block1Title: 'De BioMath a Luna29',
    block1Text1: 'Dans cet ecosysteme, plus de 200 services et outils sont en cours de developpement pour aider les personnes a observer et comprendre leur dynamique biologique.',
    block1Text2: 'Luna29 est l un de ces services. Nous avons compris qu une partie de ce travail pouvait exister de facon autonome: aider les femmes a observer calmement leurs rythmes internes et a les traduire en clarte.',
    block2Title: 'Le focus de Luna29',
    block2Text1: 'Luna29 repond a un besoin simple: faire une pause, observer les signaux internes et clarifier ce qui se passe dans le corps et l esprit.',
    block2Text2: 'Derriere Luna29, il y a des annees de modelisation numerique, de structures de donnees physiologiques et d etudes des patterns biologiques de long terme.',
    finalTitle: 'Une couche pratique distillee',
    finalText1: 'Luna29 represente une partie pratique et distillee de ce travail.',
    finalText2: 'Elle ne diagnostique pas et ne traite pas. Elle propose un environnement numerique calme ou rythmes physiologiques, observations personnelles et reflexion se rencontrent.',
    finalText3: 'Dans l ecosysteme BioMath, Luna29 n est qu une piece d une vision plus large. A elle seule, c est un outil simple et accessible pour la vie quotidienne.',
  },
  de: {
    eyebrow: 'Uber',
    title: 'Uber Luna29',
    lead: 'Luna29 entstand in einem deutlich groesseren Forschungsumfeld.',
    intro: 'Seit vielen Jahren arbeitet unser Team an BioMath, einer langfristigen digitalen Modellierungsinitiative, die untersucht, wie sich der menschliche Koerper im Zeitverlauf veraendert.',
    block1Title: 'Von BioMath zu Luna29',
    block1Text1: 'Innerhalb dieses groesseren Systems entstehen ueber 200 Services und Tools, die Menschen helfen sollen, ihre biologische Dynamik besser zu beobachten und zu verstehen.',
    block1Text2: 'Luna29 ist einer dieser Services. Waehrend der Entwicklung wurde klar, dass ein Teil davon eigenstaendig funktionieren kann: Frauen dabei zu helfen, innere Rhythmen ruhig zu beobachten und in klare Einsicht zu uebersetzen.',
    block2Title: 'Worauf Luna29 fokussiert',
    block2Text1: 'Luna29 konzentriert sich auf ein einfaches, oft uebersehenes Beduerfnis: innehalten, innere Signale wahrnehmen und ein klares Bild vom aktuellen Zustand in Koerper und Geist bilden.',
    block2Text2: 'Hinter Luna29 stehen Jahre an digitaler Modellierung, physiologischen Datenstrukturen und Forschung zu langfristigen biologischen Mustern.',
    finalTitle: 'Ein verdichteter praktischer Teil',
    finalText1: 'Luna29 ist ein verdichteter, praktischer Teil dieser Arbeit.',
    finalText2: 'Luna29 diagnostiziert oder behandelt nicht. Stattdessen bietet sie einen ruhigen digitalen Raum, in dem Rhythmen, Beobachtungen und Reflexion zu Klarheit fuehren.',
    finalText3: 'Im BioMath-Oekosystem ist Luna29 ein Teil einer groesseren Vision. Fuer sich ist es ein einfaches Werkzeug fuer alltagstaugliche Klarheit.',
  },
  zh: {
    eyebrow: '关于',
    title: '关于 Luna29',
    lead: 'Luna29 诞生于一个更大的长期研究环境。',
    intro: '多年来，我们团队一直在推进名为 BioMath 的长期项目。这是一个数字建模计划，目标是理解人体如何随时间变化。BioMath 研究生理节律、生物信号、行为模式及其复杂互动。',
    block1Title: '从 BioMath 到 Luna29',
    block1Text1: '在这个更大的系统中，我们正在开发 200 多个服务和工具，帮助人们更好地观察并理解自身的生物动力学。',
    block1Text2: 'Luna29 是其中之一。在 BioMath 的开发过程中，我们发现有一部分工作可以独立存在：帮助女性平静地观察内在节律，并将这些信号转化为清晰理解。',
    block2Title: 'Luna29 的核心',
    block2Text1: 'Luna29 专注于一个常被忽视但非常重要的能力：暂停、观察内部信号，并形成当下身心状态的清晰图景。',
    block2Text2: 'Luna29 背后是多年数字建模、人体生理数据结构研究以及长期生物模式研究的积累。',
    finalTitle: '可落地的精炼成果',
    finalText1: 'Luna29 是这项大规模工作的一个精炼且实用的部分。',
    finalText2: '它不做诊断，也不做治疗。它提供一个安静的数字环境，让生理节律、个人观察与反思汇聚成更深层的清晰感。',
    finalText3: '在更广阔的 BioMath 生态中，Luna29 只是其中一块拼图；但作为独立产品，它把深层研究以平静、易用的方式带入日常生活。',
  },
  ja: {
    eyebrow: '概要',
    title: 'Luna29 について',
    lead: 'Luna29 は、より大きな研究環境の中で生まれました。',
    intro: '私たちのチームは長年にわたり、BioMath という長期プロジェクトに取り組んできました。これは、人間の身体が時間とともにどう変化するかを理解するためのデジタルモデリングの取り組みです。',
    block1Title: 'BioMath から Luna29 へ',
    block1Text1: 'この大きなシステムの中で、200 を超えるサービスとツールが開発されており、個々の生体ダイナミクスをよりよく観察・理解できるように設計されています。',
    block1Text2: 'Luna29 はその一つです。BioMath 開発の過程で、女性が内的リズムを落ち着いて観察し、信号を明確な理解へ変換する部分は独立して成立すると分かりました。',
    block2Title: 'Luna29 の焦点',
    block2Text1: 'Luna29 は、見落とされがちなシンプルなニーズに焦点を当てます。立ち止まり、内側の信号を観察し、心身で何が起きているかを明確に捉えることです。',
    block2Text2: 'Luna29 の背後には、デジタルモデリング、生理データ構造、長期的な生物学的パターン研究の積み重ねがあります。',
    finalTitle: '実用に落とし込んだ要素',
    finalText1: 'Luna29 は、その研究の中から抽出された実用的なレイヤーです。',
    finalText2: '診断や治療を目的とせず、静かなデジタル環境の中で、生理リズム・個人観察・リフレクションを結び、より深い明瞭さを生みます。',
    finalText3: 'BioMath 全体では Luna29 は大きなビジョンの一部ですが、単体でも日常に研究知見を届けるシンプルで使いやすいツールです。',
  },
  pt: {
    eyebrow: 'Sobre',
    title: 'Sobre Luna29',
    lead: 'A Luna29 nasceu dentro de um ambiente de pesquisa muito maior.',
    intro: 'Por muitos anos, nossa equipe vem trabalhando no BioMath, uma iniciativa de modelagem digital focada em entender como o corpo humano muda ao longo do tempo.',
    block1Title: 'De BioMath para Luna29',
    block1Text1: 'Dentro desse sistema mais amplo, mais de 200 servicos e ferramentas estao sendo desenvolvidos para ajudar as pessoas a observar e entender melhor sua dinamica biologica.',
    block1Text2: 'Luna29 e um desses servicos. Durante o desenvolvimento do BioMath percebemos que uma parte desse trabalho poderia existir de forma independente: ajudar mulheres a observar ritmos internos com calma e transformar sinais em clareza.',
    block2Title: 'No que a Luna29 foca',
    block2Text1: 'Luna29 foca em uma necessidade simples e muitas vezes ignorada: pausar, observar sinais internos e formar uma visao clara do que esta acontecendo no corpo e na mente.',
    block2Text2: 'Por tras da Luna29 ha anos de modelagem digital, estruturas de dados da fisiologia humana e estudo de padroes biologicos de longo prazo.',
    finalTitle: 'Uma camada pratica destilada',
    finalText1: 'A Luna29 representa uma parte pratica e destilada desse trabalho.',
    finalText2: 'Ela nao tenta diagnosticar nem tratar. Em vez disso, oferece um ambiente digital calmo onde ritmos fisiologicos, observacoes pessoais e reflexao se unem para gerar clareza.',
    finalText3: 'No ecossistema BioMath, Luna29 e uma parte de uma visao muito maior. Sozinha, e uma ferramenta simples para trazer essa pesquisa ao dia a dia de forma acessivel.',
  },
  ar: {
    eyebrow: 'عن المشروع',
    title: 'عن Luna29',
    lead: 'وُلدت Luna29 داخل بيئة بحثية أوسع بكثير.',
    intro: 'على مدى سنوات، يعمل فريقنا على مشروع طويل الأمد يُدعى BioMath — مبادرة نمذجة رقمية تهدف إلى فهم كيف يتغيّر جسم الإنسان مع الزمن. يستكشف BioMath الإيقاعات الفسيولوجية والإشارات البيولوجية وأنماط السلوك والتفاعلات المعقّدة بينها التي تشكّل الطاقة والمزاج والتعافي.',
    block1Title: 'من BioMath إلى Luna29',
    block1Text1: 'ضمن هذا النظام الأوسع، يجري تطوير أكثر من 200 خدمة وأداة تساعد الناس على مراقبة وفهم ديناميكياتهم البيولوجية بشكل أفضل.',
    block1Text2: 'Luna29 إحدى هذه الخدمات. أثناء تطوير BioMath أدركنا أن جزءاً من هذا العمل — مساعدة النساء على مراقبة إيقاعاتهن الداخلية بهدوء وترجمة تلك الإشارات إلى فهم واضح — يمكن أن يقف بذاته. النتيجة هي Luna29.',
    block2Title: 'ما الذي تركّز عليه Luna29',
    block2Text1: 'تركّز Luna29 على حاجة بسيطة لكنها غالباً ما تُغفَل: القدرة على التوقّف، وملاحظة الإشارات الداخلية، وتشكيل صورة واضحة لما يحدث في الجسم والذهن في لحظة معيّنة.',
    block2Text2: 'خلف Luna29 سنوات من العمل في النمذجة الرقمية وهياكل بيانات الفسيولوجيا البشرية ودراسة الأنماط البيولوجية طويلة الأمد. لم تكن هذه الجهود في الأصل موجّهة لإنشاء تطبيق واحد.',
    finalTitle: 'طبقة عملية مُكثّفة',
    finalText1: 'Luna29 تمثّل جزءاً عملياً ومُكثّفاً من ذلك العمل.',
    finalText2: 'لا تحاول التشخيص أو العلاج. بدلاً من ذلك، تقدّم بيئة رقمية هادئة حيث تلتقي الإيقاعات الفسيولوجية والملاحظات الشخصية والتأمل لتخلق إحساساً أعمق بالوضوح.',
    finalText3: 'في منظومة BioMath الأوسع، Luna29 قطعة من رؤية أكبر بكثير. بمفردها، هي أداة بسيطة مصمّمة لجلب ذلك البحث العميق إلى الحياة اليومية بطريقة هادئة وسهلة الوصول.',
  },
  he: {
    eyebrow: 'אודות',
    title: 'על Luna29',
    lead: 'Luna29 נולדה בתוך סביבת מחקר הרבה יותר רחבה.',
    intro: 'במשך שנים רבות הצוות שלנו עובד על פרויקט ארוך טווח בשם BioMath — יוזמת מידול דיגיטלי שמטרתה להבין איך הגוף האנושי משתנה עם הזמן. העבודה מאחורי BioMath חוקרת ריתמים פיזיולוגיים, אותות ביולוגיים, דפוסי התנהגות ואת האינטראקציות המורכבות ביניהם שמעצבות אנרגיה, מצב רוח והתאוששות.',
    block1Title: 'מ-BioMath ל-Luna29',
    block1Text1: 'בתוך המערכת הרחבה יותר מזו, מפתחים יותר מ-200 שירותים וכלים שעוזרים לאנשים לצפות ולהבין טוב יותר את הדינמיקה הביולוגית שלהם.',
    block1Text2: 'Luna29 היא אחד מהשירותים האלה. במהלך פיתוח BioMath הבנו שחלק מהעבודה — לעזור לנשים לצפות בשקט בריתמים הפנימיים שלהן ולתרגם את האותות האלה להבנה ברורה — יכול לעמוד בפני עצמו. התוצאה היא Luna29.',
    block2Title: 'על מה Luna29 מתמקדת',
    block2Text1: 'Luna29 מתמקדת בצורך פשוט אך לעיתים קרובות מוזנח: היכולת לעצור, לצפות באותות פנימיים ולבנות תמונה ברורה של מה שקורה בגוף ובנפש ברגע נתון.',
    block2Text2: 'מאחורי Luna29 עומדים שנים של עבודה במידול דיגיטלי, מבני נתונים לפיזיולוגיה אנושית ולימוד דפוסים ביולוגיים ארוכי טווח. המאמצים האלה לא נועדו במקור ליצור אפליקציה אחת.',
    finalTitle: 'שכבה מעשית מזוקקת',
    finalText1: 'Luna29 מייצגת חלק מעשי ומזוקק מהעבודה הזו.',
    finalText2: 'היא לא מנסה לאבחן או לטפל. במקום זאת, היא מציעה סביבה דיגיטלית שקטה שבה ריתמים פיזיולוגיים, תצפיות אישיות ורפלקציה יכולים להיפגש וליצור תחושת בהירות עמוקה יותר.',
    finalText3: 'במערכת האקולוגית הרחבה של BioMath, Luna29 היא חלק מחזון גדול הרבה יותר. לבדה, היא כלי פשוט שנועד להביא את המחקר העמוק הזה לחיי היומיום בצורה שקטה ונגישה.',
  },};
