/**
 * English-only Personal Health Profile copy.
 * Kept as a plain object (not LangCopy) until localized UI is release-ready.
 */
export const HEALTH_PROFILE_COPY = {
  title: 'Help Luna understand your context',
  setupBody: 'Add only what feels useful. You can skip anything and change it later.',
  saveContinue: 'Save and continue',
  skip: 'Skip',
  back: 'Back',
  exitLater: 'Exit and finish later',
  edit: 'Edit',
  needsReview: 'Needs your review',
  confirmedFacts: 'Confirmed facts',
  noReview: 'Nothing needs review.',
  noConfirmed: 'No confirmed facts yet.',
  whyAsk: 'Why Luna asks this',
  whyDob: 'Age can make wellness ranges and patterns more relevant. You can skip this.',
  whyMedications: 'Medication context can prevent irrelevant explanations. Luna will not tell you to change medication.',
  whyCycle: 'Cycle context can make energy, sleep, mood, and symptom patterns more relevant. This is optional.',
  readyBasic: 'Your profile is ready for basic personalization.',
  addSleep: 'Add your sleep routine when you are ready for more relevant daily context.',
  reviewMedications: 'Review medications so Luna can avoid irrelevant explanations.',
  safety: 'Luna supports wellness reflection. She does not diagnose conditions or tell you to start, stop, or change medication.',
  memoryOff: 'Turning Memory off does not delete profile details you manually save here.',
  unavailable: 'Your health profile is temporarily unavailable. The rest of Luna remains available.',
  englishOnly: 'Health Profile is currently available in English only; other languages are not yet release-ready.',
  entryNavLabel: 'Personal Health Profile',
  entryNavCompleteSuffix: 'Complete',
  pageHeroTitle: 'Personal Health Profile',
  pageHeroLead: 'This information helps Luna personalize:',
  pageHeroBullets: [
    'Live conversations',
    'Lab interpretation',
    'Reports',
    'Timeline insights',
    'Recommendations',
  ],
  entryTodayTitle: 'Complete Your Personal Health Profile',
  entryTodayBody:
    'The more Luna knows about you, the more accurate your reports, insights and recommendations become.',
  entryCompletionLabel: 'Completion',
  entryContinue: 'Continue',
  entryContinueArrow: 'Continue →',
  continue: 'Continue profile',
  entryDismiss: 'Dismiss',
  entryUpdateProfile: 'Update Profile',
  entryLabsTitle: 'Personalize Lab Interpretation',
  entryLabsNotice: 'Complete your Personal Health Profile to improve interpretation.',
  entryReportsNotice:
    'Reports become more personalized when your Personal Health Profile is complete.',
  entryLiveReminder: 'A more complete Personal Health Profile can make Live replies more relevant.',
  entryLiveBySection: {
    family_history: "I still don't know your family history.",
    health_history: "I still don't know your family history.",
    medications: "We haven't discussed your medications.",
    sleep: "We don't yet have your sleep routine.",
    nutrition: "We haven't talked about your nutrition patterns yet.",
    activity: "We don't yet know your activity routine.",
    stress: "We haven't captured your stress context yet.",
    goals: "We don't yet know what you'd like Luna to focus on.",
  } as Record<string, string>,
  entrySettingsShortcut: 'Personal Health Profile',
  entryPublicTitle: 'Personal Health Profile',
  entryPublicBody:
    'Private and secure. You control what you share. Luna uses confirmed details only to personalize reflections, reports, and Live — never to diagnose or prescribe.',
  entryPublicBullets: [
    'Private',
    'Secure',
    'Controlled by you',
    'Used only for personalization',
    'Can be updated anytime',
  ],
  memorySourcesTitle: 'Different information sources',
  memorySourcesBody:
    'Manual profile information, Memory observations, and Live conversations are different sources. Completing your Personal Health Profile does not turn Memory on.',
  memoryProfileCompletion: 'Personal Health Profile completion',
  badgeUsing: 'Using',
  badgeMissing: 'Missing',
  badgeSources: {
    labs: 'Labs',
    profile: 'Profile',
    timeline: 'Timeline',
    memory: 'Memory',
    today: 'Today',
  },
  missingLabels: {
    family_history: 'Family History',
    health_history: 'Family History',
    medications: 'Current Medications',
    sleep: 'Lifestyle',
    nutrition: 'Lifestyle',
    activity: 'Lifestyle',
    stress: 'Lifestyle',
    about: 'About you',
    body: 'Body',
    goals: 'Goals',
    womens_health: "Women's health",
    care_context: 'Care context',
    data_sources: 'Data sources',
  } as Record<string, string>,
  sections: {
    about: 'About you',
    body: 'Body',
    health_history: 'Health history',
    medications: 'Medications',
    family_history: 'Family history',
    sleep: 'Sleep',
    nutrition: 'Nutrition',
    activity: 'Activity',
    stress: 'Stress',
    womens_health: "Women's health",
    goals: 'Goals',
    care_context: 'Care context',
    data_sources: 'Data sources',
  },
} as const;

export type HealthProfileSection = keyof typeof HEALTH_PROFILE_COPY.sections;
