import { Language, LangCopy, getLang } from '../constants';

export type InstallGuideCopy = {
  title: string;
  how: string;
  intro: string;
  iosTitle: string;
  androidTitle: string;
  iosStep1: string;
  iosStep2: string;
  androidStep1: string;
  androidStep2: string;
  desktopTitle: string;
  desktopStep1: string;
  desktopStep2: string;
  openDesktopPrompt: string;
  fallback: string;
  close: string;
  openPrompt: string;
  shortIos: string;
  shortAndroid: string;
  shortDesktop: string;
};

const INSTALL_GUIDE_BY_LANG: LangCopy<InstallGuideCopy> = {
  en: {
    title: 'Install App',
    how: 'How Install Works',
    intro: 'Install adds Luna29 to your home screen and opens full-screen like an app.',
    iosTitle: 'iPhone Install',
    androidTitle: 'Android Install',
    iosStep1: 'Step 1: Open Luna29 in Safari.',
    iosStep2: 'Step 2: Tap Share and choose Add to Home Screen.',
    androidStep1: 'Step 1: Open Luna29 in Chrome/Edge.',
    androidStep2: 'Step 2: Tap browser menu and choose Install App.',
    desktopTitle: 'Desktop Install',
    desktopStep1: 'Step 1: Open Luna29 in Chrome or Edge.',
    desktopStep2: 'Step 2: Click Install in the address bar or browser menu.',
    openDesktopPrompt: 'Install Luna29 on Desktop',
    fallback: 'Open Safari → Share → Add to Home Screen.',
    close: 'Close',
    openPrompt: 'Open Android Install',
    shortIos: 'Safari → Share → Add to Home Screen.',
    shortAndroid: 'Chrome menu → Install App.',
    shortDesktop: 'Use Chrome or Edge menu → Install Luna29.',
  },
  ru: {
    title: 'Установить приложение',
    how: 'Как работает установка',
    intro: 'Установка добавляет Luna29 на домашний экран и открывает в полноэкранном режиме как приложение.',
    iosTitle: 'Установка на iPhone',
    androidTitle: 'Установка на Android',
    iosStep1: 'Шаг 1: Откройте Luna29 в Safari.',
    iosStep2: 'Шаг 2: Нажмите «Поделиться» и выберите «На экран Домой».',
    androidStep1: 'Шаг 1: Откройте Luna29 в Chrome/Edge.',
    androidStep2: 'Шаг 2: Откройте меню браузера и выберите «Установить приложение».',
    desktopTitle: 'Установка на компьютер',
    desktopStep1: 'Шаг 1: Откройте Luna29 в Chrome или Edge.',
    desktopStep2: 'Шаг 2: Нажмите «Установить» в адресной строке или меню браузера.',
    openDesktopPrompt: 'Установить Luna29 на компьютер',
    fallback: 'Safari → Поделиться → На экран Домой.',
    close: 'Закрыть',
    openPrompt: 'Открыть установку Android',
    shortIos: 'Safari → Поделиться → На экран Домой.',
    shortAndroid: 'Меню Chrome → Установить приложение.',
    shortDesktop: 'Меню Chrome или Edge → Установить Luna29.',
  },
  uk: {
    title: 'Встановити застосунок',
    how: 'Як працює встановлення',
    intro: 'Встановлення додає Luna29 на домашній екран і відкриває повноекранно як застосунок.',
    iosTitle: 'Встановлення на iPhone',
    androidTitle: 'Встановлення на Android',
    iosStep1: 'Крок 1: Відкрийте Luna29 у Safari.',
    iosStep2: 'Крок 2: Натисніть «Поділитися» і оберіть «На початковий екран».',
    androidStep1: 'Крок 1: Відкрийте Luna29 у Chrome/Edge.',
    androidStep2: 'Крок 2: Відкрийте меню браузера і оберіть «Встановити застосунок».',
    desktopTitle: 'Встановлення на комп’ютер',
    desktopStep1: 'Крок 1: Відкрийте Luna29 у Chrome або Edge.',
    desktopStep2: 'Крок 2: Натисніть «Встановити» в адресному рядку або меню браузера.',
    openDesktopPrompt: 'Встановити Luna29 на комп’ютер',
    fallback: 'Safari → Поділитися → На початковий екран.',
    close: 'Закрити',
    openPrompt: 'Відкрити встановлення Android',
    shortIos: 'Safari → Поділитися → На початковий екран.',
    shortAndroid: 'Меню Chrome → Встановити застосунок.',
    shortDesktop: 'Меню Chrome або Edge → Встановити Luna29.',
  },
  es: {
    title: 'Instalar app',
    how: 'Cómo funciona la instalación',
    intro: 'La instalación añade Luna29 a tu pantalla de inicio y la abre a pantalla completa como una app.',
    iosTitle: 'Instalación en iPhone',
    androidTitle: 'Instalación en Android',
    iosStep1: 'Paso 1: Abre Luna29 en Safari.',
    iosStep2: 'Paso 2: Toca Compartir y elige Añadir a pantalla de inicio.',
    androidStep1: 'Paso 1: Abre Luna29 en Chrome/Edge.',
    androidStep2: 'Paso 2: Abre el menú del navegador y elige Instalar app.',
    desktopTitle: 'Instalación en escritorio',
    desktopStep1: 'Paso 1: Abre Luna29 en Chrome o Edge.',
    desktopStep2: 'Paso 2: Haz clic en Instalar en la barra de direcciones o en el menú.',
    openDesktopPrompt: 'Instalar Luna29 en el ordenador',
    fallback: 'Safari → Compartir → Añadir a pantalla de inicio.',
    close: 'Cerrar',
    openPrompt: 'Abrir instalación Android',
    shortIos: 'Safari → Compartir → Añadir a pantalla de inicio.',
    shortAndroid: 'Menú de Chrome → Instalar app.',
    shortDesktop: 'Menú de Chrome o Edge → Instalar Luna29.',
  },
  fr: {
    title: 'Installer l’app',
    how: 'Comment fonctionne l’installation',
    intro: 'L’installation ajoute Luna29 à l’écran d’accueil et l’ouvre en plein écran comme une app.',
    iosTitle: 'Installation iPhone',
    androidTitle: 'Installation Android',
    iosStep1: 'Étape 1 : Ouvrez Luna29 dans Safari.',
    iosStep2: 'Étape 2 : Appuyez sur Partager puis Ajouter à l’écran d’accueil.',
    androidStep1: 'Étape 1 : Ouvrez Luna29 dans Chrome/Edge.',
    androidStep2: 'Étape 2 : Ouvrez le menu du navigateur et choisissez Installer l’application.',
    desktopTitle: 'Installation ordinateur',
    desktopStep1: 'Étape 1 : Ouvrez Luna29 dans Chrome ou Edge.',
    desktopStep2: 'Étape 2 : Cliquez sur Installer dans la barre d’adresse ou le menu.',
    openDesktopPrompt: 'Installer Luna29 sur l’ordinateur',
    fallback: 'Safari → Partager → Ajouter à l’écran d’accueil.',
    close: 'Fermer',
    openPrompt: 'Ouvrir l’installation Android',
    shortIos: 'Safari → Partager → Ajouter à l’écran d’accueil.',
    shortAndroid: 'Menu Chrome → Installer l’application.',
    shortDesktop: 'Menu Chrome ou Edge → Installer Luna29.',
  },
  de: {
    title: 'App installieren',
    how: 'So funktioniert die Installation',
    intro: 'Die Installation fügt Luna29 zum Home-Bildschirm hinzu und öffnet sie im Vollbild wie eine App.',
    iosTitle: 'iPhone-Installation',
    androidTitle: 'Android-Installation',
    iosStep1: 'Schritt 1: Öffne Luna29 in Safari.',
    iosStep2: 'Schritt 2: Tippe auf Teilen und wähle Zum Home-Bildschirm.',
    androidStep1: 'Schritt 1: Öffne Luna29 in Chrome/Edge.',
    androidStep2: 'Schritt 2: Öffne das Browser-Menü und wähle App installieren.',
    desktopTitle: 'Desktop-Installation',
    desktopStep1: 'Schritt 1: Öffne Luna29 in Chrome oder Edge.',
    desktopStep2: 'Schritt 2: Klicke auf Installieren in der Adressleiste oder im Menü.',
    openDesktopPrompt: 'Luna29 auf dem Computer installieren',
    fallback: 'Safari → Teilen → Zum Home-Bildschirm.',
    close: 'Schließen',
    openPrompt: 'Android-Installation öffnen',
    shortIos: 'Safari → Teilen → Zum Home-Bildschirm.',
    shortAndroid: 'Chrome-Menü → App installieren.',
    shortDesktop: 'Chrome- oder Edge-Menü → Luna29 installieren.',
  },
  zh: {
    title: '安装应用',
    how: '安装如何运作',
    intro: '安装会将 Luna29 添加到主屏幕，并以全屏应用方式打开。',
    iosTitle: 'iPhone 安装',
    androidTitle: 'Android 安装',
    iosStep1: '步骤 1：在 Safari 中打开 Luna29。',
    iosStep2: '步骤 2：点按分享，选择添加到主屏幕。',
    androidStep1: '步骤 1：在 Chrome/Edge 中打开 Luna29。',
    androidStep2: '步骤 2：打开浏览器菜单，选择安装应用。',
    desktopTitle: '电脑安装',
    desktopStep1: '步骤 1：在 Chrome 或 Edge 中打开 Luna29。',
    desktopStep2: '步骤 2：点击地址栏或菜单中的“安装”。',
    openDesktopPrompt: '在电脑上安装 Luna29',
    fallback: 'Safari → 分享 → 添加到主屏幕。',
    close: '关闭',
    openPrompt: '打开 Android 安装',
    shortIos: 'Safari → 分享 → 添加到主屏幕。',
    shortAndroid: 'Chrome 菜单 → 安装应用。',
    shortDesktop: 'Chrome 或 Edge 菜单 → 安装 Luna29。',
  },
  ja: {
    title: 'アプリをインストール',
    how: 'インストールの仕組み',
    intro: 'インストールすると Luna29 がホーム画面に追加され、アプリのように全画面で開きます。',
    iosTitle: 'iPhone へのインストール',
    androidTitle: 'Android へのインストール',
    iosStep1: '手順 1: Safari で Luna29 を開きます。',
    iosStep2: '手順 2: 共有をタップし、「ホーム画面に追加」を選びます。',
    androidStep1: '手順 1: Chrome/Edge で Luna29 を開きます。',
    androidStep2: '手順 2: ブラウザメニューから「アプリをインストール」を選びます。',
    desktopTitle: 'パソコンへのインストール',
    desktopStep1: '手順 1: Chrome または Edge で Luna29 を開きます。',
    desktopStep2: '手順 2: アドレスバーまたはメニューの「インストール」をクリックします。',
    openDesktopPrompt: 'パソコンに Luna29 をインストール',
    fallback: 'Safari → 共有 → ホーム画面に追加。',
    close: '閉じる',
    openPrompt: 'Android インストールを開く',
    shortIos: 'Safari → 共有 → ホーム画面に追加。',
    shortAndroid: 'Chrome メニュー → アプリをインストール。',
    shortDesktop: 'Chrome または Edge メニュー → Luna29 をインストール。',
  },
  pt: {
    title: 'Instalar app',
    how: 'Como funciona a instalação',
    intro: 'A instalação adiciona o Luna29 à tela inicial e abre em tela cheia como um app.',
    iosTitle: 'Instalação no iPhone',
    androidTitle: 'Instalação no Android',
    iosStep1: 'Passo 1: Abra o Luna29 no Safari.',
    iosStep2: 'Passo 2: Toque em Compartilhar e escolha Adicionar à Tela de Início.',
    androidStep1: 'Passo 1: Abra o Luna29 no Chrome/Edge.',
    androidStep2: 'Passo 2: Abra o menu do navegador e escolha Instalar app.',
    desktopTitle: 'Instalação no computador',
    desktopStep1: 'Passo 1: Abra o Luna29 no Chrome ou Edge.',
    desktopStep2: 'Passo 2: Clique em Instalar na barra de endereço ou no menu.',
    openDesktopPrompt: 'Instalar Luna29 no computador',
    fallback: 'Safari → Compartilhar → Adicionar à Tela de Início.',
    close: 'Fechar',
    openPrompt: 'Abrir instalação Android',
    shortIos: 'Safari → Compartilhar → Adicionar à Tela de Início.',
    shortAndroid: 'Menu do Chrome → Instalar app.',
    shortDesktop: 'Menu do Chrome ou Edge → Instalar Luna29.',
  },
  ar: {
    title: 'تثبيت التطبيق',
    how: 'كيف يعمل التثبيت',
    intro: 'يضيف التثبيت Luna29 إلى الشاشة الرئيسية ويفتح بملء الشاشة كتطبيق.',
    iosTitle: 'تثبيت iPhone',
    androidTitle: 'تثبيت Android',
    iosStep1: 'الخطوة 1: افتحي Luna29 في Safari.',
    iosStep2: 'الخطوة 2: اضغطي مشاركة واختاري «إضافة إلى الشاشة الرئيسية».',
    androidStep1: 'الخطوة 1: افتحي Luna29 في Chrome/Edge.',
    androidStep2: 'الخطوة 2: اضغطي قائمة المتصفح واختاري «تثبيت التطبيق».',
    desktopTitle: 'تثبيت سطح المكتب',
    desktopStep1: 'الخطوة 1: افتحي Luna29 في Chrome أو Edge.',
    desktopStep2: 'الخطوة 2: انقري تثبيت في شريط العنوان أو قائمة المتصفح.',
    openDesktopPrompt: 'تثبيت Luna29 على الكمبيوتر',
    fallback: 'Safari → مشاركة → إضافة إلى الشاشة الرئيسية.',
    close: 'إغلاق',
    openPrompt: 'فتح تثبيت Android',
    shortIos: 'Safari → مشاركة → إضافة إلى الشاشة الرئيسية.',
    shortAndroid: 'قائمة Chrome → تثبيت التطبيق.',
    shortDesktop: 'قائمة Chrome أو Edge → تثبيت Luna29.',
  },
  he: {
    title: 'התקנת אפליקציה',
    how: 'איך ההתקנה עובדת',
    intro: 'ההתקנה מוסיפה את Luna29 למסך הבית ופותחת במסך מלא כמו אפליקציה.',
    iosTitle: 'התקנה ב-iPhone',
    androidTitle: 'התקנה ב-Android',
    iosStep1: 'שלב 1: פתחי את Luna29 ב-Safari.',
    iosStep2: 'שלב 2: הקישי שיתוף ובחרי «הוספה למסך הבית».',
    androidStep1: 'שלב 1: פתחי את Luna29 ב-Chrome/Edge.',
    androidStep2: 'שלב 2: הקישי בתפריט הדפדפן ובחרי «התקנת אפליקציה».',
    desktopTitle: 'התקנה במחשב',
    desktopStep1: 'שלב 1: פתחי את Luna29 ב-Chrome או Edge.',
    desktopStep2: 'שלב 2: לחצי על התקנה בשורת הכתובת או בתפריט.',
    openDesktopPrompt: 'התקנת Luna29 במחשב',
    fallback: 'Safari → שיתוף → הוספה למסך הבית.',
    close: 'סגירה',
    openPrompt: 'פתיחת התקנת Android',
    shortIos: 'Safari → שיתוף → הוספה למסך הבית.',
    shortAndroid: 'תפריט Chrome → התקנת אפליקציה.',
    shortDesktop: 'תפריט Chrome או Edge → התקנת Luna29.',
  },
};

export const getInstallGuideCopy = (lang: Language): InstallGuideCopy =>
  getLang(INSTALL_GUIDE_BY_LANG, lang) || INSTALL_GUIDE_BY_LANG.en;
