import { LangCopy, Language, getLang } from '../constants';

export type MemberNavCopy = {
  groupMain: string;
  groupDaily: string;
  groupInsights: string;
  groupPractice: string;
  groupHelp: string;
  groupAdmin: string;
  today: string;
  yourStory: string;
  rhythm: string;
  knowledge: string;
  you: string;
  myDay: string;
  voiceReflection: string;
  voiceFiles: string;
  memberHome: string;
  healthReports: string;
  yourMonth: string;
  unlockInsights: string;
  bridge: string;
  relationships: string;
  family: string;
  creativeStudio: string;
  medicationNotes: string;
  resetRoom: string;
  faq: string;
  partnerFaq: string;
  rhythmCalendar: string;
  adminConsole: string;
  speak: string;
  story: string;
  checkinCta: string;
};

export const MEMBER_NAV_COPY: LangCopy<MemberNavCopy> = {
  en: {
    groupMain: 'Main',
    groupDaily: 'Daily',
    groupInsights: 'Insights',
    groupPractice: 'Practice',
    groupHelp: 'Help',
    groupAdmin: 'Administration',
    today: 'Today',
    yourStory: 'Your Story',
    rhythm: 'Rhythm',
    knowledge: 'Knowledge',
    you: 'You',
    myDay: 'My Day with Luna29',
    voiceReflection: 'Voice Reflection',
    voiceFiles: 'My Voice Files',
    memberHome: 'Member Home',
    healthReports: 'Health Reports',
    yourMonth: 'Your month with Luna29',
    unlockInsights: 'Unlock Insights',
    bridge: 'The Bridge',
    relationships: 'Relationships',
    family: 'Family',
    creativeStudio: 'Creative Studio',
    medicationNotes: 'Medication Notes',
    resetRoom: 'Reset Room',
    faq: 'FAQ',
    partnerFaq: 'Partner FAQ',
    rhythmCalendar: 'Rhythm Calendar',
    adminConsole: 'Admin Console',
    speak: 'Speak',
    story: 'Story',
    checkinCta: 'Check-in',
  },
  ru: {
    groupMain: 'Главное',
    groupDaily: 'Ежедневно',
    groupInsights: 'Инсайты',
    groupPractice: 'Практика',
    groupHelp: 'Помощь',
    groupAdmin: 'Администрирование',
    today: 'Сегодня',
    yourStory: 'Ваша история',
    rhythm: 'Ритм',
    knowledge: 'Знания',
    you: 'Вы',
    myDay: 'Мой день с Luna29',
    voiceReflection: 'Голосовая рефлексия',
    voiceFiles: 'Мои голосовые файлы',
    memberHome: 'Дом участника',
    healthReports: 'Отчёты здоровья',
    yourMonth: 'Ваш месяц с Luna29',
    unlockInsights: 'Открыть инсайты',
    bridge: 'Мост',
    relationships: 'Отношения',
    family: 'Семья',
    creativeStudio: 'Творческая студия',
    medicationNotes: 'Заметки о лекарствах',
    resetRoom: 'Комната восстановления',
    faq: 'FAQ',
    partnerFaq: 'FAQ для партнёра',
    rhythmCalendar: 'Календарь ритма',
    adminConsole: 'Админ-консоль',
    speak: 'Говорить',
    story: 'История',
    checkinCta: 'Отметиться',
  },
  uk: {
    groupMain: 'Головне',
    groupDaily: 'Щодня',
    groupInsights: 'Інсайти',
    groupPractice: 'Практика',
    groupHelp: 'Допомога',
    groupAdmin: 'Адміністрування',
    today: 'Сьогодні',
    yourStory: 'Ваша історія',
    rhythm: 'Ритм',
    knowledge: 'Знання',
    you: 'Ви',
    myDay: 'Мій день з Luna29',
    voiceReflection: 'Голосова рефлексія',
    voiceFiles: 'Мої голосові файли',
    memberHome: 'Дім учасниці',
    healthReports: 'Звіти здоровʼя',
    yourMonth: 'Ваш місяць з Luna29',
    unlockInsights: 'Відкрити інсайти',
    bridge: 'Міст',
    relationships: 'Стосунки',
    family: "Сім'я",
    creativeStudio: 'Творча студія',
    medicationNotes: 'Нотатки про ліки',
    resetRoom: 'Кімната відновлення',
    faq: 'FAQ',
    partnerFaq: 'FAQ для партнера',
    rhythmCalendar: 'Календар ритму',
    adminConsole: 'Адмін-консоль',
    speak: 'Говорити',
    story: 'Історія',
    checkinCta: 'Чек-ін',
  },
  es: {
    groupMain: 'Principal',
    groupDaily: 'Diario',
    groupInsights: 'Insights',
    groupPractice: 'Práctica',
    groupHelp: 'Ayuda',
    groupAdmin: 'Administración',
    today: 'Hoy',
    yourStory: 'Tu historia',
    rhythm: 'Ritmo',
    knowledge: 'Conocimiento',
    you: 'Tú',
    myDay: 'Mi día con Luna29',
    voiceReflection: 'Reflexión por voz',
    voiceFiles: 'Mis archivos de voz',
    memberHome: 'Inicio miembro',
    healthReports: 'Informes de salud',
    yourMonth: 'Tu mes con Luna29',
    unlockInsights: 'Desbloquear insights',
    bridge: 'El Puente',
    relationships: 'Relaciones',
    family: 'Familia',
    creativeStudio: 'Estudio creativo',
    medicationNotes: 'Notas de medicación',
    resetRoom: 'Sala Reset',
    faq: 'FAQ',
    partnerFaq: 'FAQ para pareja',
    rhythmCalendar: 'Calendario de ritmo',
    adminConsole: 'Consola admin',
    speak: 'Hablar',
    story: 'Historia',
    checkinCta: 'Check-in',
  },
  fr: {
    groupMain: 'Principal',
    groupDaily: 'Quotidien',
    groupInsights: 'Insights',
    groupPractice: 'Pratique',
    groupHelp: 'Aide',
    groupAdmin: 'Administration',
    today: "Aujourd'hui",
    yourStory: 'Votre histoire',
    rhythm: 'Rythme',
    knowledge: 'Connaissance',
    you: 'Vous',
    myDay: 'Ma journée avec Luna29',
    voiceReflection: 'Réflexion vocale',
    voiceFiles: 'Mes fichiers vocaux',
    memberHome: 'Accueil membre',
    healthReports: 'Rapports santé',
    yourMonth: 'Votre mois avec Luna29',
    unlockInsights: 'Débloquer les insights',
    bridge: 'Le Pont',
    relationships: 'Relations',
    family: 'Famille',
    creativeStudio: 'Studio créatif',
    medicationNotes: 'Notes médicaments',
    resetRoom: 'Salle Reset',
    faq: 'FAQ',
    partnerFaq: 'FAQ partenaire',
    rhythmCalendar: 'Calendrier du rythme',
    adminConsole: 'Console admin',
    speak: 'Parler',
    story: 'Histoire',
    checkinCta: 'Check-in',
  },
  de: {
    groupMain: 'Hauptmenü',
    groupDaily: 'Täglich',
    groupInsights: 'Insights',
    groupPractice: 'Praxis',
    groupHelp: 'Hilfe',
    groupAdmin: 'Administration',
    today: 'Heute',
    yourStory: 'Deine Geschichte',
    rhythm: 'Rhythmus',
    knowledge: 'Wissen',
    you: 'Du',
    myDay: 'Mein Tag mit Luna29',
    voiceReflection: 'Sprachreflexion',
    voiceFiles: 'Meine Sprachdateien',
    memberHome: 'Mitglieder-Start',
    healthReports: 'Gesundheitsberichte',
    yourMonth: 'Dein Monat mit Luna29',
    unlockInsights: 'Insights freischalten',
    bridge: 'Die Brücke',
    relationships: 'Beziehungen',
    family: 'Familie',
    creativeStudio: 'Kreativstudio',
    medicationNotes: 'Medikamentennotizen',
    resetRoom: 'Reset-Raum',
    faq: 'FAQ',
    partnerFaq: 'Partner-FAQ',
    rhythmCalendar: 'Rhythmus-Kalender',
    adminConsole: 'Admin-Konsole',
    speak: 'Sprechen',
    story: 'Geschichte',
    checkinCta: 'Check-in',
  },
  zh: {
    groupMain: '主要',
    groupDaily: '每日',
    groupInsights: '洞察',
    groupPractice: '练习',
    groupHelp: '帮助',
    groupAdmin: '管理',
    today: '今天',
    yourStory: '你的故事',
    rhythm: '节律',
    knowledge: '知识',
    you: '你',
    myDay: '与 Luna29 的一天',
    voiceReflection: '语音反思',
    voiceFiles: '我的语音文件',
    memberHome: '会员主页',
    healthReports: '健康报告',
    yourMonth: '与 Luna29 的一月',
    unlockInsights: '解锁洞察',
    bridge: '连接桥',
    relationships: '关系',
    family: '家庭',
    creativeStudio: '创意工作室',
    medicationNotes: '用药笔记',
    resetRoom: '重置空间',
    faq: '常见问题',
    partnerFaq: '伴侣 FAQ',
    rhythmCalendar: '节律日历',
    adminConsole: '管理控制台',
    speak: '说话',
    story: '故事',
    checkinCta: '签到',
  },
  ja: {
    groupMain: 'メイン',
    groupDaily: '毎日',
    groupInsights: 'インサイト',
    groupPractice: 'プラクティス',
    groupHelp: 'ヘルプ',
    groupAdmin: '管理',
    today: '今日',
    yourStory: 'あなたのストーリー',
    rhythm: 'リズム',
    knowledge: 'ナレッジ',
    you: 'あなた',
    myDay: 'Luna29との一日',
    voiceReflection: '音声リフレクション',
    voiceFiles: '音声ファイル',
    memberHome: 'メンバーホーム',
    healthReports: 'ヘルスレポート',
    yourMonth: 'Luna29との一か月',
    unlockInsights: 'インサイトを解除',
    bridge: 'ブリッジ',
    relationships: '関係',
    family: 'ファミリー',
    creativeStudio: 'クリエイティブスタジオ',
    medicationNotes: '服薬メモ',
    resetRoom: 'リセットルーム',
    faq: 'FAQ',
    partnerFaq: 'パートナーFAQ',
    rhythmCalendar: 'リズムカレンダー',
    adminConsole: '管理コンソール',
    speak: '話す',
    story: 'ストーリー',
    checkinCta: 'チェックイン',
  },
  pt: {
    groupMain: 'Principal',
    groupDaily: 'Diário',
    groupInsights: 'Insights',
    groupPractice: 'Prática',
    groupHelp: 'Ajuda',
    groupAdmin: 'Administração',
    today: 'Hoje',
    yourStory: 'Sua história',
    rhythm: 'Ritmo',
    knowledge: 'Conhecimento',
    you: 'Você',
    myDay: 'Meu dia com Luna29',
    voiceReflection: 'Reflexão por voz',
    voiceFiles: 'Meus arquivos de voz',
    memberHome: 'Início membro',
    healthReports: 'Relatórios de saúde',
    yourMonth: 'Seu mês com Luna29',
    unlockInsights: 'Desbloquear insights',
    bridge: 'A Ponte',
    relationships: 'Relacionamentos',
    family: 'Família',
    creativeStudio: 'Estúdio criativo',
    medicationNotes: 'Notas de medicação',
    resetRoom: 'Sala Reset',
    faq: 'FAQ',
    partnerFaq: 'FAQ para parceiro',
    rhythmCalendar: 'Calendário de ritmo',
    adminConsole: 'Console admin',
    speak: 'Falar',
    story: 'História',
    checkinCta: 'Check-in',
  },
  ar: {
    groupMain: 'الرئيسية',
    groupDaily: 'يومي',
    groupInsights: 'رؤى',
    groupPractice: 'ممارسة',
    groupHelp: 'مساعدة',
    groupAdmin: 'الإدارة',
    today: 'اليوم',
    yourStory: 'قصتك',
    rhythm: 'الإيقاع',
    knowledge: 'المعرفة',
    you: 'أنت',
    myDay: 'يومي مع Luna29',
    voiceReflection: 'تأمل صوتي',
    voiceFiles: 'ملفاتي الصوتية',
    memberHome: 'رئيسية العضو',
    healthReports: 'تقارير الصحة',
    yourMonth: 'شهرك مع Luna29',
    unlockInsights: 'فتح الرؤى',
    bridge: 'الجسر',
    relationships: 'العلاقات',
    family: 'العائلة',
    creativeStudio: 'استوديو إبداعي',
    medicationNotes: 'ملاحظات الأدوية',
    resetRoom: 'غرفة إعادة التوازن',
    faq: 'الأسئلة الشائعة',
    partnerFaq: 'أسئلة الشريك',
    rhythmCalendar: 'تقويم الإيقاع',
    adminConsole: 'لوحة الإدارة',
    speak: 'تحدث',
    story: 'القصة',
    checkinCta: 'تسجيل',
  },
  he: {
    groupMain: 'ראשי',
    groupDaily: 'יומי',
    groupInsights: 'תובנות',
    groupPractice: 'תרגול',
    groupHelp: 'עזרה',
    groupAdmin: 'ניהול',
    today: 'היום',
    yourStory: 'הסיפור שלך',
    rhythm: 'קצב',
    knowledge: 'ידע',
    you: 'את',
    myDay: 'היום שלי עם Luna29',
    voiceReflection: 'רפלקציה קולית',
    voiceFiles: 'קבצי הקול שלי',
    memberHome: 'בית חבר',
    healthReports: 'דוחות בריאות',
    yourMonth: 'החודש שלך עם Luna29',
    unlockInsights: 'פתיחת תובנות',
    bridge: 'הגשר',
    relationships: 'יחסים',
    family: 'משפחה',
    creativeStudio: 'סטודיו יצירתי',
    medicationNotes: 'הערות תרופות',
    resetRoom: 'חדר איפוס',
    faq: 'שאלות נפוצות',
    partnerFaq: 'שאלות בן/בת זוג',
    rhythmCalendar: 'לוח קצב',
    adminConsole: 'קונסולת ניהול',
    speak: 'דברי',
    story: 'סיפור',
    checkinCta: 'צ׳ק-אין',
  },
};

export const getMemberNavCopy = (lang: Language): MemberNavCopy =>
  getLang(MEMBER_NAV_COPY, lang) || MEMBER_NAV_COPY.en;
