import { LangCopy, Language, getLang } from '../constants';

export type PublicHomeContent = {
  heroTitle: string;
  heroTitleAlt: string;
  heroSubtitle: string;
  heroTagline: string;
  diffBadge: string;
  trustLine: string;
  doorCalmTitle: string;
  doorCalmBody: string;
  doorCalmCta: string;
  doorDemoTitle: string;
  doorDemoBody: string;
  doorDemoCta: string;
  trialCta: string;
  freeCta: string;
  patternTitle: string;
  patternCardLabel: string;
  patternOne: string;
  patternTwo: string;
  bridgeTeaserTitle: string;
  bridgeTeaserBody: string;
  bridgeTeaserCta: string;
  bridgePartnerNote: string;
  finalTitle: string;
  finalBody: string;
  finalTrialCta: string;
  finalFreeCta: string;
  pricingLink: string;
};

const publicHomeContentByLang: LangCopy<PublicHomeContent> = {
  en: {
    heroTitle: 'Interpretation, not prediction',
    heroTitleAlt: 'Your body has a language — Luna29 helps you read it',
    heroSubtitle: 'A calm mirror for how your body feels across your cycle — and how to talk about it with people you love.',
    heroTagline: 'Luna29 — The physiology of feeling.',
    diffBadge: 'Not another period tracker',
    trustLine: 'Your data stays close · Never sold · Not a medical diagnosis',
    doorCalmTitle: 'Need gentleness first?',
    doorCalmBody: 'Ritual Path — a minute a day, no streaks, no guilt.',
    doorCalmCta: 'Explore Ritual Path',
    doorDemoTitle: 'Want to see it first?',
    doorDemoBody: 'Rhythm Calendar demo — your cycle as an editorial map, not red dots.',
    doorDemoCta: 'Open calendar demo',
    trialCta: 'Start 7-day free trial',
    freeCta: 'Create free account',
    patternTitle: 'Patterns women recognize',
    patternCardLabel: 'Pattern noticed',
    patternOne: 'Energy drops two days before cycle — not laziness',
    patternTwo: 'Sleep under 6h raises emotional sensitivity before ovulation',
    bridgeTeaserTitle: 'Hard to explain today to your partner?',
    bridgeTeaserBody: 'The Bridge turns inner weather into calm words — for yourself or someone you trust.',
    bridgeTeaserCta: 'See The Bridge',
    bridgePartnerNote: 'Partner FAQ available inside your private space.',
    finalTitle: 'Begin observing your rhythm',
    finalBody: 'Free tier forever: check-in, voice notes, and 2 Bridge reflections per week.',
    finalTrialCta: 'Start free trial',
    finalFreeCta: 'Stay on free plan',
    pricingLink: 'Compare plans',
  },
  ru: {
    heroTitle: 'Интерпретация, а не предсказание',
    heroTitleAlt: 'У тела есть язык — Luna29 помогает его прочитать',
    heroSubtitle: 'Спокойное зеркало того, как тело чувствует себя в цикле — и как говорить об этом с близкими.',
    heroTagline: 'Luna29 — физиология чувств.',
    diffBadge: 'Не очередной трекер месячных',
    trustLine: 'Данные рядом с вами · Никогда не продаём · Не медицинский диагноз',
    doorCalmTitle: 'Сначала нужна мягкость?',
    doorCalmBody: 'Ритуальный путь — минута в день, без streak и чувства вины.',
    doorCalmCta: 'Открыть Ritual Path',
    doorDemoTitle: 'Хотите сначала посмотреть?',
    doorDemoBody: 'Демо Rhythm Calendar — цикл как editorial-карта, не красные точки.',
    doorDemoCta: 'Открыть демо календаря',
    trialCta: 'Начать trial на 7 дней',
    freeCta: 'Создать бесплатный аккаунт',
    patternTitle: 'Паттерны, которые узнают',
    patternCardLabel: 'Паттерн замечен',
    patternOne: 'Энергия падает за два дня до цикла — это не лень',
    patternTwo: 'Сон меньше 6 часов усиливает чувствительность перед овуляцией',
    bridgeTeaserTitle: 'Сложно объяснить партнёру, как вы сегодня?',
    bridgeTeaserBody: 'Мост переводит внутреннюю погоду в спокойные слова — для себя или близкого.',
    bridgeTeaserCta: 'Открыть The Bridge',
    bridgePartnerNote: 'Partner FAQ — в вашем приватном пространстве.',
    finalTitle: 'Начните наблюдать свой ритм',
    finalBody: 'Free tier навсегда: check-in, голос и 2 Bridge в неделю.',
    finalTrialCta: 'Начать trial',
    finalFreeCta: 'Остаться на free',
    pricingLink: 'Сравнить планы',
  },
  uk: {
    heroTitle: 'Інтерпретація, а не передбачення',
    heroTitleAlt: 'У тіла є мова — Luna29 допомагає її прочитати',
    heroSubtitle: 'Спокійне дзеркало того, як тіло відчуває себе в циклі — і як говорити про це з близькими.',
    heroTagline: 'Luna29 — фізіологія відчуттів.',
    diffBadge: 'Не черговий трекер циклу',
    trustLine: 'Дані поруч із вами · Ніколи не продаємо · Не медичний діагноз',
    doorCalmTitle: 'Спочатку потрібна м’якість?',
    doorCalmBody: 'Ритуальний шлях — хвилина на день, без streak і провини.',
    doorCalmCta: 'Відкрити Ritual Path',
    doorDemoTitle: 'Хочете спочатку подивитися?',
    doorDemoBody: 'Демо Rhythm Calendar — цикл як editorial-мапа, не червоні точки.',
    doorDemoCta: 'Відкрити демо календаря',
    trialCta: 'Почати trial на 7 днів',
    freeCta: 'Створити безкоштовний акаунт',
    patternTitle: 'Патерни, які впізнають',
    patternCardLabel: 'Патерн помічено',
    patternOne: 'Енергія падає за два дні до циклу — це не лінощі',
    patternTwo: 'Сон менше 6 годин підвищує чутливість перед овуляцією',
    bridgeTeaserTitle: 'Важко пояснити партнеру, як ви сьогодні?',
    bridgeTeaserBody: 'Міст перекладає внутрішню погоду у спокійні слова — для себе чи близької людини.',
    bridgeTeaserCta: 'Відкрити The Bridge',
    bridgePartnerNote: 'Partner FAQ — у вашому приватному просторі.',
    finalTitle: 'Почніть спостерігати свій ритм',
    finalBody: 'Free tier назавжди: check-in, голос і 2 Bridge на тиждень.',
    finalTrialCta: 'Почати trial',
    finalFreeCta: 'Залишитися на free',
    pricingLink: 'Порівняти плани',
  },
  es: {
    heroTitle: 'Interpretacion, no prediccion',
    heroTitleAlt: 'Tu cuerpo tiene un lenguaje — Luna29 te ayuda a leerlo',
    heroSubtitle: 'Un espejo calmado de como se siente tu cuerpo en el ciclo — y como hablarlo con quienes amas.',
    heroTagline: 'Luna29 — la fisiologia del sentir.',
    diffBadge: 'No otro rastreador de periodo',
    trustLine: 'Tus datos cerca · Nunca se venden · No es diagnostico medico',
    doorCalmTitle: 'Primero necesitas suavidad?',
    doorCalmBody: 'Ritual Path — un minuto al dia, sin rachas ni culpa.',
    doorCalmCta: 'Ver Ritual Path',
    doorDemoTitle: 'Quieres verlo primero?',
    doorDemoBody: 'Demo del calendario — tu ciclo como mapa editorial, no puntos rojos.',
    doorDemoCta: 'Abrir demo del calendario',
    trialCta: 'Iniciar prueba de 7 dias',
    freeCta: 'Crear cuenta gratis',
    patternTitle: 'Patrones que reconoces',
    patternCardLabel: 'Patron notado',
    patternOne: 'La energia baja dos dias antes del ciclo — no es pereza',
    patternTwo: 'Dormir menos de 6h aumenta la sensibilidad emocional',
    bridgeTeaserTitle: 'Dificil explicar hoy a tu pareja?',
    bridgeTeaserBody: 'The Bridge convierte tu clima interior en palabras calmadas.',
    bridgeTeaserCta: 'Ver The Bridge',
    bridgePartnerNote: 'Partner FAQ dentro de tu espacio privado.',
    finalTitle: 'Empieza a observar tu ritmo',
    finalBody: 'Plan gratis para siempre: check-in, voz y 2 Bridge por semana.',
    finalTrialCta: 'Iniciar prueba gratis',
    finalFreeCta: 'Quedarme en plan gratis',
    pricingLink: 'Comparar planes',
  },
  fr: {
    heroTitle: 'Interpretation, pas prediction',
    heroTitleAlt: 'Votre corps a un langage — Luna29 vous aide a le lire',
    heroSubtitle: 'Un miroir calme de ce que votre corps ressent dans le cycle — et comment en parler.',
    heroTagline: 'Luna29 — la physiologie du ressenti.',
    diffBadge: 'Pas un autre tracker de regles',
    trustLine: 'Vos donnees restent proches · Jamais vendues · Pas un diagnostic medical',
    doorCalmTitle: 'Besoin de douceur d abord?',
    doorCalmBody: 'Ritual Path — une minute par jour, sans streak ni culpabilite.',
    doorCalmCta: 'Voir Ritual Path',
    doorDemoTitle: 'Voir d abord?',
    doorDemoBody: 'Demo calendrier — votre cycle comme carte editoriale.',
    doorDemoCta: 'Ouvrir la demo',
    trialCta: 'Essai gratuit 7 jours',
    freeCta: 'Creer un compte gratuit',
    patternTitle: 'Des patterns que l on reconnait',
    patternCardLabel: 'Pattern remarque',
    patternOne: 'L energie baisse deux jours avant le cycle — ce n est pas de la paresse',
    patternTwo: 'Moins de 6h de sommeil augmente la sensibilite emotionnelle',
    bridgeTeaserTitle: 'Difficile d expliquer votre jour a votre partenaire?',
    bridgeTeaserBody: 'The Bridge traduit votre meteo interieure en mots calmes.',
    bridgeTeaserCta: 'Voir The Bridge',
    bridgePartnerNote: 'Partner FAQ dans votre espace prive.',
    finalTitle: 'Commencez a observer votre rythme',
    finalBody: 'Gratuit pour toujours : check-in, voix et 2 Bridge par semaine.',
    finalTrialCta: 'Commencer l essai',
    finalFreeCta: 'Rester en gratuit',
    pricingLink: 'Comparer les plans',
  },
  de: {
    heroTitle: 'Interpretation, nicht Vorhersage',
    heroTitleAlt: 'Ihr Koerper hat eine Sprache — Luna29 hilft beim Lesen',
    heroSubtitle: 'Ein ruhiger Spiegel dafuer, wie sich Ihr Koerper im Zyklus anfuehlt — und wie Sie darueber sprechen.',
    heroTagline: 'Luna29 — die Physiologie des Fuehlens.',
    diffBadge: 'Kein weiterer Perioden-Tracker',
    trustLine: 'Ihre Daten bleiben nah · Niemals verkauft · Keine medizinische Diagnose',
    doorCalmTitle: 'Zuerst Sanftheit noetig?',
    doorCalmBody: 'Ritual Path — eine Minute am Tag, ohne Streaks und Schuld.',
    doorCalmCta: 'Ritual Path ansehen',
    doorDemoTitle: 'Erst ansehen?',
    doorDemoBody: 'Kalender-Demo — Ihr Zyklus als editorial map, nicht rote Punkte.',
    doorDemoCta: 'Kalender-Demo oeffnen',
    trialCta: '7-Tage-Test starten',
    freeCta: 'Kostenloses Konto erstellen',
    patternTitle: 'Muster, die Sie erkennen',
    patternCardLabel: 'Muster bemerkt',
    patternOne: 'Energie sinkt zwei Tage vor dem Zyklus — keine Faulheit',
    patternTwo: 'Weniger als 6h Schlaf erhoeht emotionale Sensibilitaet',
    bridgeTeaserTitle: 'Schwer, heute Ihrem Partner zu erklaeren?',
    bridgeTeaserBody: 'The Bridge macht aus innerem Wetter ruhige Worte.',
    bridgeTeaserCta: 'The Bridge ansehen',
    bridgePartnerNote: 'Partner FAQ in Ihrem privaten Bereich.',
    finalTitle: 'Beginnen Sie, Ihren Rhythmus zu beobachten',
    finalBody: 'Free tier fuer immer: Check-in, Stimme und 2 Bridge pro Woche.',
    finalTrialCta: 'Test starten',
    finalFreeCta: 'Beim Free-Plan bleiben',
    pricingLink: 'Plaene vergleichen',
  },
  zh: {
    heroTitle: '解读，而非预测',
    heroTitleAlt: '身体有自己的语言 — Luna29 帮你读懂它',
    heroSubtitle: '平静地映照身体在周期中的感受——以及如何与所爱的人谈论它。',
    heroTagline: 'Luna29 — 感受的生理学。',
    diffBadge: '不是又一个经期追踪器',
    trustLine: '数据留在身边 · 永不出售 · 非医疗诊断',
    doorCalmTitle: '需要先温柔一点？',
    doorCalmBody: '仪式路径 — 每天一分钟，无连续打卡，无内疚。',
    doorCalmCta: '了解仪式路径',
    doorDemoTitle: '想先看看？',
    doorDemoBody: '节律日历演示 — 周期如编辑式地图，而非红点。',
    doorDemoCta: '打开日历演示',
    trialCta: '开始 7 天免费试用',
    freeCta: '创建免费账户',
    patternTitle: '女性熟悉的模式',
    patternCardLabel: '注意到的模式',
    patternOne: '周期前两天精力下降 — 不是懒惰',
    patternTwo: '睡眠少于 6 小时会在排卵前提高情绪敏感',
    bridgeTeaserTitle: '很难向伴侣解释今天的状态？',
    bridgeTeaserBody: '连接桥将内在天气转化为平静的语言。',
    bridgeTeaserCta: '了解连接桥',
    bridgePartnerNote: '伴侣 FAQ 在您的私人空间中。',
    finalTitle: '开始观察你的节律',
    finalBody: '永久免费层：签到、语音笔记，每周 2 次 Bridge。',
    finalTrialCta: '开始免费试用',
    finalFreeCta: '继续使用免费方案',
    pricingLink: '比较方案',
  },
  ja: {
    heroTitle: '予測ではなく、解釈',
    heroTitleAlt: '身体には言語がある — Luna29が読み取りを助けます',
    heroSubtitle: '周期の中で身体がどう感じるかを静かに映す鏡 — 大切な人との会話のために。',
    heroTagline: 'Luna29 — 感覚の生理学。',
    diffBadge: 'また別の生理アプリではありません',
    trustLine: 'データは身近に · 売却しません · 医療診断ではありません',
    doorCalmTitle: 'まずやさしさが必要？',
    doorCalmBody: 'リチュアルパス — 1日1分、ストリークも罪悪感もなし。',
    doorCalmCta: 'リチュアルパスを見る',
    doorDemoTitle: 'まず見てみたい？',
    doorDemoBody: 'リズムカレンダーデモ — 赤い点ではなく、編集的な周期マップ。',
    doorDemoCta: 'カレンダーデモを開く',
    trialCta: '7日間無料トライアル',
    freeCta: '無料アカウント作成',
    patternTitle: '女性が知っているパターン',
    patternCardLabel: 'パターンに気づく',
    patternOne: '周期の2日前にエネルギーが下がる — 怠けではありません',
    patternTwo: '6時間未満の睡眠は感情の敏感さを高めます',
    bridgeTeaserTitle: '今日の状態をパートナーに説明するのが難しい？',
    bridgeTeaserBody: 'ブリッジは内側の天気を穏やかな言葉に変えます。',
    bridgeTeaserCta: 'ブリッジを見る',
    bridgePartnerNote: 'Partner FAQはプライベート空間内で。',
    finalTitle: 'リズムの観察を始める',
    finalBody: '永久無料：チェックイン、音声、Bridge週2回。',
    finalTrialCta: '無料トライアル開始',
    finalFreeCta: '無料プランのまま',
    pricingLink: 'プランを比較',
  },
  pt: {
    heroTitle: 'Interpretacao, nao previsao',
    heroTitleAlt: 'Seu corpo tem uma linguagem — Luna29 ajuda a le-la',
    heroSubtitle: 'Um espelho calmo de como seu corpo sente o ciclo — e como falar sobre isso.',
    heroTagline: 'Luna29 — a fisiologia do sentir.',
    diffBadge: 'Nao e mais um rastreador de ciclo',
    trustLine: 'Seus dados perto de voce · Nunca vendidos · Nao e diagnostico medico',
    doorCalmTitle: 'Precisa de gentileza primeiro?',
    doorCalmBody: 'Ritual Path — um minuto por dia, sem streaks ou culpa.',
    doorCalmCta: 'Ver Ritual Path',
    doorDemoTitle: 'Quer ver antes?',
    doorDemoBody: 'Demo do calendario — ciclo como mapa editorial, nao pontos vermelhos.',
    doorDemoCta: 'Abrir demo do calendario',
    trialCta: 'Iniciar teste de 7 dias',
    freeCta: 'Criar conta gratis',
    patternTitle: 'Padroes que voce reconhece',
    patternCardLabel: 'Padrao notado',
    patternOne: 'Energia cai dois dias antes do ciclo — nao e preguica',
    patternTwo: 'Dormir menos de 6h aumenta sensibilidade emocional',
    bridgeTeaserTitle: 'Dificil explicar hoje ao parceiro?',
    bridgeTeaserBody: 'The Bridge transforma clima interior em palavras calmas.',
    bridgeTeaserCta: 'Ver The Bridge',
    bridgePartnerNote: 'Partner FAQ no seu espaco privado.',
    finalTitle: 'Comece a observar seu ritmo',
    finalBody: 'Plano gratis para sempre: check-in, voz e 2 Bridge por semana.',
    finalTrialCta: 'Iniciar teste gratis',
    finalFreeCta: 'Ficar no plano gratis',
    pricingLink: 'Comparar planos',
  },
  ar: {
    heroTitle: 'تفسير، لا تنبؤ',
    heroTitleAlt: 'لجسدك لغة — Luna29 تساعدك على قراءتها',
    heroSubtitle: 'مرآة هادئة لما يشعر به جسدك عبر دورتك — وكيف تتحدثين عنه مع من تحبين.',
    heroTagline: 'Luna29 — فسيولوجيا الشعور.',
    diffBadge: 'ليس متتبع دورة آخر',
    trustLine: 'بياناتك قريبة منك · لا تُباع أبداً · ليس تشخيصاً طبياً',
    doorCalmTitle: 'تحتاجين اللطف أولاً؟',
    doorCalmBody: 'Ritual Path — دقيقة في اليوم، بلا streaks أو ذنب.',
    doorCalmCta: 'استكشفي Ritual Path',
    doorDemoTitle: 'تريدين رؤيته أولاً؟',
    doorDemoBody: 'عرض Rhythm Calendar — دورتك كخريطة editorial، لا نقاط حمراء.',
    doorDemoCta: 'افتحي عرض التقويم',
    trialCta: 'ابدئي تجربة مجانية 7 أيام',
    freeCta: 'أنشئي حساباً مجانياً',
    patternTitle: 'أنماط تتعرّف عليها النساء',
    patternCardLabel: 'نمط مُلاحظ',
    patternOne: 'الطاقة تنخفض قبل الدورة بيومين — ليس كسلاً',
    patternTwo: 'النوم أقل من 6 ساعات يرفع الحساسية العاطفية',
    bridgeTeaserTitle: 'صعب أن تشرحي لشريكك كيف تشعرين اليوم؟',
    bridgeTeaserBody: 'الجسر يحوّل الطقس الداخلي إلى كلمات هادئة — لنفسك أو لمن تثقين به.',
    bridgeTeaserCta: 'اكتشفي The Bridge',
    bridgePartnerNote: 'Partner FAQ متاح في مساحتك الخاصة.',
    finalTitle: 'ابدئي ملاحظة إيقاعك',
    finalBody: 'الخطة المجانية للأبد: check-in، ملاحظات صوتية، و2 Bridge أسبوعياً.',
    finalTrialCta: 'ابدئي التجربة المجانية',
    finalFreeCta: 'ابقي على الخطة المجانية',
    pricingLink: 'قارني الخطط',
  },
  he: {
    heroTitle: 'פרשנות, לא חיזוי',
    heroTitleAlt: 'לגוף שלך יש שפה — Luna29 עוזרת לך לקרוא אותה',
    heroSubtitle: 'מראה שקטה לאיך הגוף שלך מרגיש במחזור — ואיך לדבר על זה עם מי שאת אוהבת.',
    heroTagline: 'Luna29 — הפיזיולוגיה של התחושה.',
    diffBadge: 'לא עוד מעקב מחזור',
    trustLine: 'הנתונים שלך קרובים אלייך · לעולם לא נמכרים · לא אבחון רפואי',
    doorCalmTitle: 'צריכה עדינות קודם?',
    doorCalmBody: 'Ritual Path — דקה ביום, בלי streaks או אשמה.',
    doorCalmCta: 'גלי Ritual Path',
    doorDemoTitle: 'רוצה לראות קודם?',
    doorDemoBody: 'דמו Rhythm Calendar — המחזור כמפת editorial, לא נקודות אדומות.',
    doorDemoCta: 'פתחי דמו לוח שנה',
    trialCta: 'התחילי ניסיון חינם ל-7 ימים',
    freeCta: 'צרי חשבון חינם',
    patternTitle: 'דפוסים שנשים מזהות',
    patternCardLabel: 'דפוס שזוהה',
    patternOne: 'האנרגיה יורדת יומיים לפני המחזור — זה לא עצלנות',
    patternTwo: 'שינה מתחת ל-6 שעות מעלה רגישות רגשית לפני הביוץ',
    bridgeTeaserTitle: 'קשה להסביר לבן/בת הזוג איך את היום?',
    bridgeTeaserBody: 'הגשר הופך מזג פנימי למילים שקטות — לעצמך או למי שאת סומכת עליו/עליה.',
    bridgeTeaserCta: 'ראי את The Bridge',
    bridgePartnerNote: 'Partner FAQ זמין במרחב הפרטי שלך.',
    finalTitle: 'התחילי לצפות בקצב שלך',
    finalBody: 'תוכנית חינם לנצח: check-in, הערות קול ו-2 Bridge בשבוע.',
    finalTrialCta: 'התחילי ניסיון חינם',
    finalFreeCta: 'הישארי בתוכנית החינמית',
    pricingLink: 'השווי תוכניות',
  },
};

export const getPublicHomeContent = (lang: Language, variant: 'a' | 'b' = 'a'): PublicHomeContent => {
  const base = getLang(publicHomeContentByLang, lang) || publicHomeContentByLang.en;
  if (variant === 'b') {
    return { ...base, heroTitle: base.heroTitleAlt || base.heroTitle };
  }
  return base;
};
