import { LangCopy } from '../../constants';
import { LegalDocContent } from './types';

export const LEGAL_DATA_RIGHTS: LangCopy<LegalDocContent> = {
  en: {
    title: 'Your Data',
    subtitle: 'Consumer privacy rights, local export, and deletion controls for Luna29. Disclosures aligned with CCPA/CPRA where applicable.',
    sections: [
      { heading: 'Applicability', body: 'This notice describes privacy rights available to residents of California and other U.S. states with comprehensive consumer privacy laws. It supplements our Privacy Notice. Luna29 is a wellness application with local-first storage; many wellness records remain on your device unless you use optional server-linked features.' },
      { heading: 'Right to Know and Access', body: 'You may request disclosure of the categories and specific pieces of personal information we have collected about you, the sources, purposes, categories of recipients, and retention periods. We will respond within the timeframes required by applicable law after verifying your request.' },
      { heading: 'Right to Delete', body: 'You may request deletion of personal information we maintain, subject to exceptions for completing transactions, security, legal compliance, internal uses reasonably aligned with your expectations, or other grounds permitted by law. Local device data can often be deleted immediately through in-app controls below.' },
      { heading: 'Right to Correct', body: 'You may request correction of inaccurate personal information we maintain about you. Because core wellness data may be stored locally, correcting records on your device may be the fastest path for journal and check-in entries.' },
      { heading: 'Right to Opt-Out of Sale or Sharing', body: 'Luna29 does not sell personal information as defined under California and similar state laws. We do not share personal information for cross-context behavioral advertising. No opt-out link is required for sale/share because we do not engage in those activities.' },
      { heading: 'Non-Discrimination', body: 'We will not discriminate against you for exercising applicable privacy rights, including by denying goods or services, charging different prices, or providing a different level of quality, except as permitted by law.' },
      { heading: 'How to Submit Requests', body: 'Submit privacy requests through the Contact page or built-in controls below. We may verify your identity before fulfilling requests. Authorized agents may submit requests on your behalf with proof of authorization. If we deny a request, you may appeal as provided by applicable state law.' },
    ],
  },
  ru: {
    title: 'Ваши данные',
    subtitle: 'Права потребителей на конфиденциальность, локальный экспорт и удаление данных в Luna29. Раскрытия в духе CCPA/CPRA, где применимо.',
    sections: [
      { heading: 'Применимость', body: 'Настоящее уведомление описывает права на конфиденциальность для резидентов Калифорнии и других штатов США с комплексными законами о защите данных. Оно дополняет Уведомление о конфиденциальности. Luna29 — wellness-приложение с local-first хранением; многие записи остаются на устройстве, если вы не используете опциональные серверные функции.' },
      { heading: 'Право знать и получить доступ', body: 'Вы можете запросить раскрытие категорий и конкретных фрагментов собранной персональной информации, источников, целей, категорий получателей и сроков хранения. Мы ответим в сроки, требуемые применимым правом, после верификации запроса.' },
      { heading: 'Право на удаление', body: 'Вы можете запросить удаление персональной информации, которую мы храним, с исключениями для завершения транзакций, безопасности, правового compliance, внутреннего использования, согласованного с вашими ожиданиями, или иных оснований, разрешённых законом. Локальные данные часто можно удалить сразу через элементы управления ниже.' },
      { heading: 'Право на исправление', body: 'Вы можете запросить исправление неточной персональной информации. Поскольку основные wellness-данные могут храниться локально, исправление записей на устройстве может быть самым быстрым путём для дневника и check-in.' },
      { heading: 'Право отказа от продажи или передачи', body: 'Luna29 не продаёт персональную информацию в смысле законов Калифорнии и аналогичных штатов. Мы не передаём персональную информацию для поведенческой рекламы между контекстами. Ссылка opt-out для продажи/передачи не требуется, так как мы не занимаемся этими activities.' },
      { heading: 'Запрет дискриминации', body: 'Мы не будем дискриминировать вас за реализацию применимых прав на конфиденциальность, включая отказ в товарах или услугах, иные цены или уровень качества, кроме случаев, разрешённых законом.' },
      { heading: 'Как подать запрос', body: 'Подавайте запросы через страницу Contact или встроенные элементы управления ниже. Мы можем верифицировать личность перед исполнением. Уполномоченные агенты могут подавать запросы с подтверждением полномочий. При отказе вы можете обжаловать согласно применимому праву штата.' },
    ],
  },
  uk: {
    title: 'Ваші дані',
    subtitle: 'Права споживачів на конфіденційність, локальний експорт і видалення даних у Luna29. Розкриття в дусі CCPA/CPRA, де застосовно.',
    sections: [
      { heading: 'Застосовність', body: 'Це повідомлення описує права на конфіденційність для резидентів Каліфорнії та інших штатів США з комплексними законами про захист даних. Воно доповнює Повідомлення про конфіденційність. Luna29 — wellness-додаток з local-first сховищем; багато записів лишаються на пристрої, якщо ви не використовуєте опціональні серверні функції.' },
      { heading: 'Право знати та отримати доступ', body: 'Ви можете запросити розкриття категорій і конкретних фрагментів зібраної персональної інформації, джерел, цілей, категорій одержувачів і строків зберігання. Ми відповімо у строки, передбачені застосовним правом, після верифікації запиту.' },
      { heading: 'Право на видалення', body: 'Ви можете запросити видалення персональної інформації, яку ми зберігаємо, з винятками для завершення транзакцій, безпеки, правового compliance, внутрішнього використання, узгодженого з вашими очікуваннями, або інших підстав, дозволених законом. Локальні дані часто можна видалити одразу через елементи керування нижче.' },
      { heading: 'Право на виправлення', body: 'Ви можете запросити виправлення неточної персональної інформації. Оскільки основні wellness-дані можуть зберігатися локально, виправлення записів на пристрої може бути найшвидшим шляхом для щоденника та check-in.' },
      { heading: 'Право відмови від продажу або передачі', body: 'Luna29 не продає персональну інформацію у значенні законів Каліфорнії та аналогічних штатів. Ми не передаємо персональну інформацію для поведінкової реклами між контекстами. Посилання opt-out для продажу/передачі не потрібне, оскільки ми не займаємося цими activities.' },
      { heading: 'Заборона дискримінації', body: 'Ми не будемо discriminate against вас за реалізацію застосовних прав на конфіденційність, включно з відмовою в товарах або послугах, іншими цінами чи рівнем якості, крім випадків, дозволених законом.' },
      { heading: 'Як подати запит', body: 'Подавайте запити через сторінку Contact або вбудовані елементи керування нижче. Ми можемо верифікувати особу перед виконанням. Уповноважені агенти можуть подавати запити з підтвердженням повноважень. У разі відмови ви можете оскаржити згідно із застосовним правом штату.' },
    ],
  },
  es: {
    title: 'Sus datos',
    subtitle: 'Derechos de privacidad del consumidor, exportación local y controles de eliminación para Luna29. Divulgaciones alineadas con CCPA/CPRA cuando corresponda.',
    sections: [
      { heading: 'Aplicabilidad', body: 'Este aviso describe derechos de privacidad disponibles para residentes de California y otros estados de EE. UU. con leyes integrales de privacidad del consumidor. Complementa nuestro Aviso de privacidad. Luna29 es una aplicación de bienestar con almacenamiento local-first; muchos registros permanecen en su dispositivo salvo que use funciones opcionales vinculadas al servidor.' },
      { heading: 'Derecho a saber y acceder', body: 'Puede solicitar la divulgación de categorías y piezas específicas de información personal que hayamos recopilado sobre usted, fuentes, finalidades, categorías de destinatarios y períodos de retención. Responderemos en los plazos exigidos por la ley aplicable tras verificar su solicitud.' },
      { heading: 'Derecho a eliminar', body: 'Puede solicitar la eliminación de información personal que mantengamos, sujeto a excepciones por completar transacciones, seguridad, cumplimiento legal, usos internos razonablemente alineados con sus expectativas u otros motivos permitidos por ley. Los datos locales a menudo pueden eliminarse de inmediato mediante los controles siguientes.' },
      { heading: 'Derecho a corregir', body: 'Puede solicitar la corrección de información personal inexacta que mantengamos. Dado que los datos principales de bienestar pueden almacenarse localmente, corregir registros en su dispositivo puede ser la vía más rápida para entradas de diario y check-in.' },
      { heading: 'Derecho a optar por no vender o compartir', body: 'Luna29 no vende información personal según las leyes de California y estados similares. No compartimos información personal para publicidad conductual entre contextos. No se requiere enlace de opt-out de venta/compartición porque no realizamos esas actividades.' },
      { heading: 'No discriminación', body: 'No lo discriminaremos por ejercer derechos de privacidad aplicables, incluida la negación de bienes o servicios, precios diferentes o nivel distinto de calidad, excepto según permita la ley.' },
      { heading: 'Cómo enviar solicitudes', body: 'Envíe solicitudes de privacidad por la página Contact o los controles integrados siguientes. Podemos verificar su identidad antes de cumplir. Los agentes autorizados pueden enviar solicitudes con prueba de autorización. Si denegamos una solicitud, puede apelar según la ley estatal aplicable.' },
    ],
  },
  fr: {
    title: 'Vos données',
    subtitle: 'Droits de confidentialité des consommateurs, export local et contrôles de suppression pour Luna29. Divulgations alignées sur CCPA/CPRA le cas échéant.',
    sections: [
      { heading: 'Applicabilité', body: 'Le présent avis décrit les droits de confidentialité disponibles pour les résidents de Californie et d\'autres États U.S. disposant de lois intégrales sur la vie privée des consommateurs. Il complète notre Notice de confidentialité. Luna29 est une application bien-être avec stockage local-first ; de nombreux enregistrements restent sur votre appareil sauf utilisation de fonctions optionnelles liées au serveur.' },
      { heading: 'Droit de savoir et d\'accès', body: 'Vous pouvez demander la divulgation des catégories et éléments spécifiques d\'informations personnelles collectées, des sources, finalités, catégories de destinataires et durées de conservation. Nous répondrons dans les délais exigés par la loi applicable après vérification de votre demande.' },
      { heading: 'Droit de suppression', body: 'Vous pouvez demander la suppression des informations personnelles que nous détenons, sous réserve d\'exceptions pour achever des transactions, la sécurité, la conformité légale, des usages internes raisonnablement alignés sur vos attentes ou d\'autres motifs permis par la loi. Les données locales peuvent souvent être supprimées immédiatement via les contrôles ci-dessous.' },
      { heading: 'Droit de rectification', body: 'Vous pouvez demander la correction d\'informations personnelles inexactes que nous détenons. Les données bien-être principales pouvant être stockées localement, corriger les enregistrements sur votre appareil peut être la voie la plus rapide pour journal et check-ins.' },
      { heading: 'Droit de refus de vente ou partage', body: 'Luna29 ne vend pas d\'informations personnelles au sens des lois de Californie et États similaires. Nous ne partageons pas d\'informations personnelles pour la publicité comportementale intercontextes. Aucun lien opt-out vente/partage n\'est requis car nous n\'effectuons pas ces activités.' },
      { heading: 'Non-discrimination', body: 'Nous ne vous discriminerons pas pour l\'exercice de droits de confidentialité applicables, y compris en refusant biens ou services, en appliquant des prix différents ou un niveau de qualité différent, sauf autorisation légale.' },
      { heading: 'Comment soumettre des demandes', body: 'Soumettez les demandes de confidentialité via la page Contact ou les contrôles intégrés ci-dessous. Nous pouvons vérifier votre identité avant exécution. Des agents autorisés peuvent soumettre des demandes avec preuve d\'autorisation. En cas de refus, vous pouvez faire appel conformément à la loi étatique applicable.' },
    ],
  },
  de: {
    title: 'Ihre Daten',
    subtitle: 'Verbraucher-Datenschutzrechte, lokaler Export und Löschsteuerung für Luna29. Offenlegungen im Sinne von CCPA/CPRA, soweit anwendbar.',
    sections: [
      { heading: 'Anwendbarkeit', body: 'Dieser Hinweis beschreibt Datenschutzrechte für Einwohner Kaliforniens und anderer U.S.-Bundesstaaten mit umfassenden Verbraucherdatenschutzgesetzen. Er ergänzt unseren Datenschutzhinweis. Luna29 ist eine Wellness-App mit Local-First-Speicher; viele Aufzeichnungen verbleiben auf Ihrem Gerät, sofern Sie keine optionalen servergebundenen Funktionen nutzen.' },
      { heading: 'Recht auf Auskunft und Zugang', body: 'Sie können Offenlegung der Kategorien und konkreten personenbezogenen Informationen verlangen, die wir über Sie erhoben haben, einschließlich Quellen, Zwecke, Empfängerkategorien und Aufbewahrungsfristen. Wir antworten innerhalb der gesetzlich vorgeschriebenen Fristen nach Verifizierung Ihrer Anfrage.' },
      { heading: 'Recht auf Löschung', body: 'Sie können Löschung personenbezogener Informationen verlangen, die wir speichern, vorbehaltlich Ausnahmen für Transaktionsabschluss, Sicherheit, Rechtscompliance, interne Nutzungen, die vernünftigerweise Ihren Erwartungen entsprechen, oder andere gesetzlich zulässige Gründe. Lokale Gerätedaten können oft sofort über die untenstehenden Steuerungen gelöscht werden.' },
      { heading: 'Recht auf Berichtigung', body: 'Sie können Berichtigung ungenauer personenbezogener Informationen verlangen. Da Kern-Wellness-Daten lokal gespeichert sein können, ist die Korrektur auf Ihrem Gerät oft der schnellste Weg für Tagebuch- und Check-in-Einträge.' },
      { heading: 'Recht auf Opt-Out von Verkauf oder Weitergabe', body: 'Luna29 verkauft keine personenbezogenen Informationen im Sinne kalifornischer und ähnlicher Gesetze. Wir geben keine personenbezogenen Informationen für kontextübergreifende Verhaltenswerbung weiter. Ein Opt-out-Link für Verkauf/Weitergabe ist nicht erforderlich, da wir diese Aktivitäten nicht betreiben.' },
      { heading: 'Nichtdiskriminierung', body: 'Wir werden Sie nicht für die Ausübung anwendbarer Datenschutzrechte benachteiligen, einschließlich durch Verweigerung von Waren oder Dienstleistungen, unterschiedliche Preise oder Qualitätsniveau, außer gesetzlich zulässig.' },
      { heading: 'So reichen Sie Anfragen ein', body: 'Reichen Sie Datenschutzanfragen über die Contact-Seite oder die untenstehenden integrierten Steuerungen ein. Wir können Ihre Identität vor Erfüllung verifizieren. Bevollmächtigte Agenten können Anfragen mit Nachweis der Vollmacht einreichen. Bei Ablehnung können Sie gemäß anwendbarem Landesrecht Einspruch einlegen.' },
    ],
  },
  zh: {
    title: '您的数据',
    subtitle: 'Luna29 消费者隐私权利、本地导出与删除控件。在适用情况下与 CCPA/CPRA 一致的披露。',
    sections: [
      { heading: '适用范围', body: '本声明说明加州及其他拥有全面消费者隐私法的美国州居民可享有的隐私权利，是对隐私声明的补充。Luna29 为 local-first wellness 应用；除非您使用可选服务器关联功能，许多记录保留在设备本地。' },
      { heading: '知情与访问权', body: '您可请求披露我们收集的关于您的个人信息类别及具体片段、来源、目的、接收方类别及保留期限。我们将在适用法律要求的期限内，在验证请求后回复。' },
      { heading: '删除权', body: '您可请求删除我们持有的个人信息，但完成交易、安全、法律合规、与您期望合理一致的内部使用或其他法律允许的理由除外。本地设备数据通常可通过下方控件立即删除。' },
      { heading: '更正权', body: '您可请求更正我们持有的不准确个人信息。由于核心 wellness 数据可能本地存储，在设备上更正日记与签到记录可能是最快途径。' },
      { heading: '选择退出出售或共享权', body: 'Luna29 不出售加州及类似州法所定义的个人信息，不为跨情境行为广告共享个人信息。因我们不从事此类活动，无需出售/共享 opt-out 链接。' },
      { heading: '不歧视', body: '我们不会因您行使适用的隐私权利而歧视您，包括拒绝商品或服务、收取不同价格或提供不同质量水平，法律允许的除外。' },
      { heading: '如何提交请求', body: '通过 Contact 页面或下方内置控件提交隐私请求。我们可能在履行前验证身份。授权代理人可凭授权证明代为提交。若我们拒绝请求，您可依适用州法申诉。' },
    ],
  },
  ja: {
    title: 'お客様のデータ',
    subtitle: 'Luna29 の消費者プライバシー権、ローカルエクスポート、削除コントロール。該当する場合は CCPA/CPRA に沿った開示。',
    sections: [
      { heading: '適用範囲', body: '本通知は、カリフォルニア州および包括的消費者プライバシー法を有するその他の米国州の居住者に利用可能なプライバシー権を説明します。プライバシー通知を補完します。Luna29 は local-first ストレージのウェルネスアプリです。オプションのサーバー連携機能を使用しない限り、多くの記録は端末に残ります。' },
      { heading: '知る権利およびアクセス権', body: '当社が収集した個人情報のカテゴリと具体的内容、出所、目的、受領者カテゴリ、保存期間の開示を請求できます。請求を確認後、適用法で要求される期間内に回答します。' },
      { heading: '削除権', body: '当社が保持する個人情報の削除を請求できます。取引完了、セキュリティ、法令遵守、お客様の期待と合理的に一致する内部利用、その他法令で許される理由は例外です。ローカル端末データは下記コントロールですぐに削除できる場合が多いです。' },
      { heading: '訂正権', body: '当社が保持する不正確な個人情報の訂正を請求できます。コア wellness データがローカル保存される場合、ジャーナルや check-in の訂正は端末上が最速の経路となることがあります。' },
      { heading: '販売・共有の opt-out 権', body: 'Luna29 はカリフォルニア州および類似州法で定義される個人情報を販売しません。クロスコンテキスト行動広告のために個人情報を共有しません。当該活動を行わないため、販売/共有 opt-out リンクは不要です。' },
      { heading: '非差別', body: '適用されるプライバシー権の行使により、商品・サービスの拒否、異なる価格設定、異なる品質レベルの提供等による差別は行いません（法令で許される場合を除く）。' },
      { heading: '請求の提出方法', body: 'Contact ページまたは下記組み込みコントロールからプライバシー請求を提出してください。履行前に本人確認を行う場合があります。認可された代理人は、authorization の証明を添えて請求できます。拒否された場合は、適用州法に従い異議申立てができます。' },
    ],
  },
  pt: {
    title: 'Seus dados',
    subtitle: 'Direitos de privacidade do consumidor, exportação local e controles de exclusão para a Luna29. Divulgações alinhadas ao CCPA/CPRA quando aplicável.',
    sections: [
      { heading: 'Aplicabilidade', body: 'Este aviso descreve direitos de privacidade disponíveis a residentes da Califórnia e de outros estados dos EUA com leis abrangentes de privacidade do consumidor. Complementa nosso Aviso de privacidade. A Luna29 é um aplicativo de bem-estar com armazenamento local-first; muitos registros permanecem no seu dispositivo salvo uso de recursos opcionais vinculados ao servidor.' },
      { heading: 'Direito de saber e acessar', body: 'Você pode solicitar divulgação das categorias e peças específicas de informações pessoais que coletamos sobre você, fontes, finalidades, categorias de destinatários e períodos de retenção. Responderemos nos prazos exigidos pela lei aplicável após verificar sua solicitação.' },
      { heading: 'Direito de excluir', body: 'Você pode solicitar exclusão de informações pessoais que mantemos, sujeito a exceções para concluir transações, segurança, conformidade legal, usos internos razoavelmente alinhados às suas expectativas ou outros motivos permitidos por lei. Dados locais do dispositivo muitas vezes podem ser excluídos imediatamente pelos controles abaixo.' },
      { heading: 'Direito de corrigir', body: 'Você pode solicitar correção de informações pessoais imprecisas que mantemos. Como dados principais de bem-estar podem ser armazenados localmente, corrigir registros no dispositivo pode ser o caminho mais rápido para entradas de diário e check-in.' },
      { heading: 'Direito de opt-out de venda ou compartilhamento', body: 'A Luna29 não vende informações pessoais conforme definido pelas leis da Califórnia e estados similares. Não compartilhamos informações pessoais para publicidade comportamental entre contextos. Nenhum link de opt-out de venda/compartilhamento é necessário porque não realizamos essas atividades.' },
      { heading: 'Não discriminação', body: 'Não o discriminaremos por exercer direitos de privacidade aplicáveis, incluindo negar bens ou serviços, cobrar preços diferentes ou fornecer nível distinto de qualidade, exceto conforme permitido por lei.' },
      { heading: 'Como enviar solicitações', body: 'Envie solicitações de privacidade pela página Contact ou controles integrados abaixo. Podemos verificar sua identidade antes de cumprir. Agentes autorizados podem enviar solicitações com prova de autorização. Se negarmos uma solicitação, você pode recorrer conforme a lei estadual aplicável.' },
    ],
  },
  ar: {
    title: 'بياناتك',
    subtitle: 'حقوق خصوصية المستهلك والتصدير المحلي وضوابط الحذف في Luna29. إفصاحات متوافقة مع CCPA/CPRA حيث ينطبق.',
    sections: [
      { heading: 'النطاق', body: 'يصف هذا الإشعار حقوق الخصوصية المتاحة لسكان كalifornia وولايات أمريكية أخرى لديها قوانين شاملة لخصوصية المستهلك. يكمّل إشعار الخصوصية. Luna29 تطبيق عافية بتخزين local-first؛ تبقى سجلات كثيرة على جهازك ما لم تستخدم ميزات اختيارية مرتبطة بالخادم.' },
      { heading: 'حق المعرفة والوصول', body: 'يمكنك طلب الإفصاح عن فئات وقطع محددة من المعلومات الشخصية التي جمعناها عنك، والمصادر والأغراض وفئات المستلمين وفترات الاحتفاظ. سنرد ضمن المهل التي يقتضيها القانون المعمول به بعد التحقق من طلبك.' },
      { heading: 'حق الحذف', body: 'يمكنك طلب حذف المعلومات الشخصية التي نحتفظ بها، مع استثناءات لإتمام المعاملات والأمان والامتثال القانوني والاستخدامات الداخلية المتوافقة reasonably مع توقعاتك أو أسباب أخرى يسمح بها القانون. غالباً يمكن حذف البيانات المحلية فوراً عبر عناصر التحكم أدناه.' },
      { heading: 'حق التصحيح', body: 'يمكنك طلب تصحيح معلومات شخصية غير دقيقة نحتفظ بها. بما أن بيانات العافية الأساسية قد تُخزَّن محلياً، قد يكون تصحيح السجلات على جهازك أسرع مسار لإدخالات اليوميات والتسجيلات.' },
      { heading: 'حق الانسحاب من البيع أو المشاركة', body: 'لا تبيع Luna29 المعلومات الشخصية كما هو معرّف بموجب قوانين كalifornia والولايات المماثلة. لا نشارك المعلومات الشخصية للإعلان السلوكي عبر السياقات. لا يلزم رابط opt-out للبيع/المشاركة لأننا لا نمارس هذه الأنشطة.' },
      { heading: 'عدم التمييز', body: 'لن نميّز ضدك لممارسة حقوق الخصوصية المعمول بها، بما في ذلك رفض السلع أو الخدمات أو فرض أسعار مختلفة أو مستوى جودة مختلف، إلا كما يسمح القانون.' },
      { heading: 'كيفية تقديم الطلبات', body: 'قدّم طلبات الخصوصية عبر صفحة Contact أو عناصر التحكم المدمجة أدناه. قد نتحقق من هويتك قبل التنفيذ. يمكن للوكلاء المعتمدين تقديم الطلبات بإثبات التفويض. إذا رفضنا طلباً، يمكنك الاستئناف وفق قانون الولاية المعمول به.' },
    ],
  },
  he: {
    title: 'הנתונים שלכם',
    subtitle: 'זכויות פרטיות צרכן, ייצוא מקומי ובקרות מחיקה עבור Luna29. גילויים בהתאם ל-CCPA/CPRA במידת החלות.',
    sections: [
      { heading: 'תחולה', body: 'הודעה זו מתארת זכויות פרטיות הזמינות לתושבי קalifornia ומדינות ארה"ב אחרות עם חוקי פרטיות צרכן מקיפים. היא משלימה את הודעת הפרטיות. Luna29 היא אפליקציית wellness עם אחסון local-first; רשומות רבות נשארות במכשיר אלא אם משתמשים בתכונות אופציונליות מקושרות לשרת.' },
      { heading: 'זכות לדעת ולגשת', body: 'ניתן לבקש גילוי קטגוריות וחלקים ספציפיים של מידע אישי שאספנו עליכם, מקורות, מטרות, קטגוריות נמענים ותקופות שמירה. נענה במסגרות שהחוק החל דורש לאחר אימות הבקשה.' },
      { heading: 'זכות למחיקה', body: 'ניתן לבקש מחיקת מידע אישי שאנו מחזיקים, בכפוף לחריגים להשלמת עסקאות, אבטחה, ציות לחוק, שימושים פנימיים התואמים באופן סביר עם ציפיותיכם או עילות אחרות שהחוק מתיר. נתונים מקומיים במכשיר ניתן לעיתים קרובות למחוק מיד באמצעות הבקרות למטה.' },
      { heading: 'זכות לתיקון', body: 'ניתן לבקש תיקון מידע אישי לא מדויק שאנו מחזיקים. מכיוון שנתוני wellness מרכזיים עשויים להיות מאוחסנים מקומית, תיקון רשומות במכשיר עשוי להיות הנתיב המהיר ביותר לרשומות יומן ו-check-in.' },
      { heading: 'זכות opt-out ממכירה או שיתוף', body: 'Luna29 אינה מוכרת מידע אישי כהגדרתו בחוקי California ומדינות דומות. איננו משתפים מידע אישי לפרסום התנהגותי חוצה-הקשרים. אין צורך בקישור opt-out למכירה/שיתוף כי איננו עוסקים בפעילויות אלה.' },
      { heading: 'אי-אפליה', body: 'לא נפלה ביחס אליכם בגין מימוש זכויות פרטיות חלות, כולל שלילת סחורות או שירותים, תמחור שונה או רמת איכות שונה, אלא כפי שהחוק מתיר.' },
      { heading: 'כיצד להגיש בקשות', body: 'הגישו בקשות פרטיות דרך דף Contact או הבקרות המובנות למטה. אנו עשויים לאמת זהות לפני מילוי. סוכנים מורשים יכולים להגיש בקשות עם הוכחת הרשאה. אם נדחה בקשה, ניתן לערער לפי דין המדינה החל.' },
    ],
  },
};
