import { LangCopy } from '../../constants';
import { LegalDocContent } from './types';

export const LEGAL_TERMS: LangCopy<LegalDocContent> = {
  en: {
    title: 'Terms of Use',
    subtitle: 'Baseline U.S. service terms governing access to Luna29 and responsible usage.',
    sections: [
      { heading: 'Acceptance of Terms', body: 'By accessing or using Luna29, you agree to these Terms of Use and our Privacy Notice. If you do not agree, do not use the service. If you use Luna29 on behalf of an organization, you represent that you have authority to bind that organization.' },
      { heading: 'Eligibility', body: 'You must be at least 18 years old, or the age of majority in your jurisdiction, to create an account or subscribe. Luna29 is not directed to children under 13. You are responsible for ensuring your use complies with applicable law in your location.' },
      { heading: 'Wellness Service; No Medical Relationship', body: 'Luna29 provides wellness, cycle-awareness, and reflective tools for informational purposes only. Use of Luna29 does not create a doctor-patient, therapist-client, or any licensed clinical provider relationship. Luna29 is not a medical device and is not cleared or approved by the FDA or any regulatory body as a diagnostic or therapeutic product.' },
      { heading: 'Accounts and Stripe Subscriptions', body: 'You are responsible for safeguarding your account credentials and for all activity under your account. Paid memberships are billed through Stripe, Inc.; payment terms, renewals, and cancellations are subject to the checkout flow and Stripe policies. We may suspend or terminate access for non-payment, fraud, or violation of these terms.' },
      { heading: 'Acceptable Use', body: 'You must not misuse Luna29, attempt unauthorized access, scrape or reverse engineer the service except as permitted by law, interfere with infrastructure, upload unlawful or harmful content, or use the service to provide emergency medical care or replace professional judgment.' },
      { heading: 'Intellectual Property', body: 'Luna29, its branding, software, and content are owned by us or our licensors and protected by intellectual property laws. We grant you a limited, non-exclusive, non-transferable license to use the service for personal, non-commercial purposes in accordance with these terms.' },
      { heading: 'Disclaimers and Limitation of Liability', body: 'Luna29 is provided "as is" and "as available" without warranties of any kind to the maximum extent permitted by law. To the fullest extent permitted, we are not liable for indirect, incidental, special, consequential, or punitive damages, or for decisions you make based on app outputs. Our aggregate liability shall not exceed the greater of amounts you paid us in the twelve months before the claim or one hundred U.S. dollars.' },
      { heading: 'Indemnification', body: 'You agree to indemnify and hold harmless Luna29 and its operators from claims arising out of your misuse of the service, violation of these terms, or infringement of third-party rights, except to the extent caused by our gross negligence or willful misconduct.' },
      { heading: 'Termination and Changes', body: 'We may suspend or terminate your access at any time for violation of these terms or to protect the service. You may stop using Luna29 at any time. We may modify features or these terms by posting updated terms with a new effective date. Continued use after changes constitutes acceptance where permitted by law.' },
      { heading: 'Governing Law and Disputes', body: 'These terms are intended to align with U.S. online service practices. Unless mandatory local law requires otherwise, disputes shall be resolved in accordance with applicable U.S. law and courts of competent jurisdiction. Contact us through the Contact page for questions about these terms.' },
    ],
  },
  ru: {
    title: 'Условия использования',
    subtitle: 'Базовые условия сервиса (ориентир США), регулирующие доступ к Luna29 и ответственное использование.',
    sections: [
      { heading: 'Принятие условий', body: 'Используя Luna29, вы соглашаетесь с настоящими Условиями и Уведомлением о конфиденциальности. Если вы не согласны, не используйте сервис. При использовании от имени организации вы подтверждаете полномочия обязать её этими условиями.' },
      { heading: 'Допустимость', body: 'Для создания аккаунта или подписки вам должно быть не менее 18 лет или возраста совершеннолетия в вашей юрисдикции. Luna29 не направлена детям младше 13 лет. Вы отвечаете за соответствие использования применимому праву.' },
      { heading: 'Wellness-сервис; без медицинских отношений', body: 'Luna29 предоставляет wellness-инструменты, осознанность цикла и рефлексию исключительно в информационных целях. Использование не создаёт отношений врач-пациент, терапевт-клиент или иных лицензированных клинических отношений. Luna29 не является медицинским устройством и не одобрена FDA или иным регулятором как диагностический или терапевтический продукт.' },
      { heading: 'Аккаунты и подписки Stripe', body: 'Вы отвечаете за сохранность учётных данных и всю активность под аккаунтом. Платные подписки оплачиваются через Stripe, Inc.; условия оплаты, продления и отмены определяются checkout и политиками Stripe. Мы можем приостановить или прекратить доступ при неоплате, мошенничестве или нарушении условий.' },
      { heading: 'Допустимое использование', body: 'Запрещено злоупотреблять Luna29, пытаться получить несанкционированный доступ, скрейпить или декомпилировать сервис (кроме случаев, разрешённых законом), нарушать инфраструктуру, загружать незаконный или вредный контент или использовать сервис для экстренной медпомощи или замены профессионального суждения.' },
      { heading: 'Интеллектуальная собственность', body: 'Luna29, брендинг, ПО и контент принадлежат нам или лицензиарам и защищены законами об ИС. Мы предоставляем ограниченную неисключительную непередаваемую лицензию на личное некоммерческое использование в соответствии с условиями.' },
      { heading: 'Отказ от гарантий и ограничение ответственности', body: 'Luna29 предоставляется «как есть» без гарантий в максимально допустимой законом степени. Мы не несём ответственности за косвенные, случайные, особые, последующие или штрафные убытки, а также за решения на основе выводов приложения. Совокупная ответственность не превышает сумму, уплаченную за 12 месяцев до претензии, или 100 USD.' },
      { heading: 'Возмещение убытков', body: 'Вы соглашаетесь возмещать убытки Luna29 и операторам по претензиям, вызванным вашим злоупотреблением, нарушением условий или прав третьих лиц, кроме случаев нашей грубой неосторожности или умышленного проступка.' },
      { heading: 'Прекращение и изменения', body: 'Мы можем приостановить или прекратить доступ при нарушении условий или для защиты сервиса. Вы можете прекратить использование в любой момент. Мы можем изменять функции или условия с новой датой вступления в силу. Продолжение использования после изменений означает принятие, где это допускается законом.' },
      { heading: 'Применимое право и споры', body: 'Условия ориентированы на практику онлайн-сервисов США. Если местное обязательное право не требует иного, споры разрешаются по применимому праву США в компетентных судах. Вопросы—через страницу Contact.' },
    ],
  },
  uk: {
    title: 'Умови використання',
    subtitle: 'Базові умови сервісу (орієнтир США), що регулюють доступ до Luna29 та відповідальне використання.',
    sections: [
      { heading: 'Прийняття умов', body: 'Користуючись Luna29, ви погоджуєтесь з цими Умовами та Повідомленням про конфіденційність. Якщо не згодні, не використовуйте сервіс. Користуючись від імені організації, ви підтверджуєте повноваження зобовʼязати її цими умовами.' },
      { heading: 'Придатність', body: 'Для створення акаунта або підписки вам має бути щонайменше 18 років або вік повноліття у вашій юрисдикції. Luna29 не спрямована на дітей молодше 13 років. Ви відповідаєте за відповідність використання застосовному праву.' },
      { heading: 'Wellness-сервіс; без медичних відносин', body: 'Luna29 надає wellness-інструменти, усвідомленість циклу та рефлексію виключно з інформаційною метою. Використання не створює відносин лікар-пацієнт, терапевт-клієнт чи інших ліцензованих клінічних відносин. Luna29 не є медичним виробом і не схвалена FDA чи іншим регулятором як діагностичний або терапевтичний продукт.' },
      { heading: 'Акаунти та підписки Stripe', body: 'Ви відповідаєте за збереження облікових даних і всю активність під акаунтом. Платні підписки оплачуються через Stripe, Inc.; умови оплати, продовження та скасування визначаються checkout і політиками Stripe. Ми можемо призупинити або припинити доступ при неоплаті, шахрайстві або порушенні умов.' },
      { heading: 'Допустиме використання', body: 'Заборонено зловживати Luna29, намагатися отримати несанкціонований доступ, скрейпити або декомпілювати сервіс (крім випадків, дозволених законом), порушувати інфраструктуру, завантажувати незаконний або шкідливий контент або використовувати сервіс для екстреної меддопомоги чи заміни професійного судження.' },
      { heading: 'Інтелектуальна власність', body: 'Luna29, брендинг, ПЗ і контент належать нам або ліцензіарам і захищені законами про ІВ. Ми надаємо обмежену невиключну невідчужувану ліцензію на особисте некомерційне використання відповідно до умов.' },
      { heading: 'Відмова від гарантій і обмеження відповідальності', body: 'Luna29 надається «як є» без гарантій у максимально дозволеній законом мірі. Ми не несемо відповідальності за непрямі, випадкові, особливі, наступні або штрафні збитки, а також за рішення на основі виводів додатку. Сумарна відповідальність не перевищує суму, сплачену за 12 місяців до претензії, або 100 USD.' },
      { heading: 'Відшкодування', body: 'Ви погоджуєтесь відшкодовувати Luna29 та операторам претензії, спричинені вашим зловживанням, порушенням умов або прав третіх осіб, крім випадків нашої грубої необережності або умисного проступку.' },
      { heading: 'Припинення та зміни', body: 'Ми можемо призупинити або припинити доступ при порушенні умов або для захисту сервісу. Ви можете припинити використання будь-коли. Ми можемо змінювати функції або умови з новою датою набуття чинності. Продовження використання після змін означає прийняття, де це дозволено законом.' },
      { heading: 'Застосовне право та спори', body: 'Умови орієнтовані на практику онлайн-сервісів США. Якщо місцеве обовʼязкове право не вимагає іншого, спори вирішуються за застосовним правом США в компетентних судах. Питання—через сторінку Contact.' },
    ],
  },
  es: {
    title: 'Términos de uso',
    subtitle: 'Términos base del servicio (orientados a EE. UU.) que rigen el acceso a Luna29 y el uso responsable.',
    sections: [
      { heading: 'Aceptación de los términos', body: 'Al acceder o usar Luna29, acepta estos Términos de uso y nuestro Aviso de privacidad. Si no está de acuerdo, no use el servicio. Si usa Luna29 en nombre de una organización, declara tener autoridad para obligarla.' },
      { heading: 'Elegibilidad', body: 'Debe tener al menos 18 años, o la mayoría de edad en su jurisdicción, para crear una cuenta o suscribirse. Luna29 no está dirigida a menores de 13 años. Usted es responsable de que su uso cumpla la ley aplicable.' },
      { heading: 'Servicio de bienestar; sin relación médica', body: 'Luna29 ofrece herramientas de bienestar, conciencia del ciclo y reflexión solo con fines informativos. Su uso no crea relación médico-paciente, terapeuta-cliente ni ninguna relación clínica licenciada. Luna29 no es un dispositivo médico ni está aprobada por la FDA u otro regulador como producto diagnóstico o terapéutico.' },
      { heading: 'Cuentas y suscripciones Stripe', body: 'Usted es responsable de proteger sus credenciales y de toda actividad bajo su cuenta. Las membresías de pago se facturan a través de Stripe, Inc.; los términos de pago, renovación y cancelación están sujetos al checkout y políticas de Stripe. Podemos suspender o terminar el acceso por impago, fraude o violación de estos términos.' },
      { heading: 'Uso aceptable', body: 'No debe hacer un uso indebido de Luna29, intentar acceso no autorizado, extraer o ingeniería inversa del servicio salvo lo permitido por ley, interferir con la infraestructura, cargar contenido ilícito o dañino, ni usar el servicio para atención médica de emergencia o sustituir el juicio profesional.' },
      { heading: 'Propiedad intelectual', body: 'Luna29, su marca, software y contenido son de nuestra propiedad o de licenciantes y están protegidos por leyes de propiedad intelectual. Le otorgamos una licencia limitada, no exclusiva e intransferible para uso personal no comercial conforme a estos términos.' },
      { heading: 'Exenciones y limitación de responsabilidad', body: 'Luna29 se proporciona «tal cual» y «según disponibilidad» sin garantías en la máxima medida permitida por ley. En la medida permitida, no somos responsables de daños indirectos, incidentales, especiales, consecuentes o punitivos, ni de decisiones basadas en salidas de la app. Nuestra responsabilidad agregada no excederá lo pagado en los doce meses anteriores a la reclamación o cien dólares estadounidenses.' },
      { heading: 'Indemnización', body: 'Usted acepta indemnizar y mantener indemne a Luna29 y sus operadores por reclamaciones derivadas de su uso indebido, violación de estos términos o infracción de derechos de terceros, excepto por nuestra negligencia grave o conducta dolosa.' },
      { heading: 'Terminación y cambios', body: 'Podemos suspender o terminar su acceso por violación de estos términos o para proteger el servicio. Puede dejar de usar Luna29 en cualquier momento. Podemos modificar funciones o estos términos publicando versiones actualizadas con nueva fecha de vigencia. El uso continuado tras cambios constituye aceptación cuando la ley lo permita.' },
      { heading: 'Ley aplicable y disputas', body: 'Estos términos se alinean con prácticas de servicios en línea de EE. UU. Salvo que la ley local imperativa exija lo contrario, las disputas se resolverán conforme a la ley aplicable de EE. UU. y tribunales competentes. Contáctenos por la página Contact para preguntas.' },
    ],
  },
  fr: {
    title: 'Conditions d\'utilisation',
    subtitle: 'Conditions de service de référence (orientées U.S.) régissant l\'accès à Luna29 et une utilisation responsable.',
    sections: [
      { heading: 'Acceptation des conditions', body: 'En accédant ou en utilisant Luna29, vous acceptez les présentes Conditions et notre Notice de confidentialité. Si vous n\'acceptez pas, n\'utilisez pas le service. Si vous utilisez Luna29 pour une organisation, vous déclarez avoir l\'autorité de l\'engager.' },
      { heading: 'Éligibilité', body: 'Vous devez avoir au moins 18 ans, ou l\'âge de la majorité dans votre juridiction, pour créer un compte ou vous abonner. Luna29 ne s\'adresse pas aux enfants de moins de 13 ans. Vous êtes responsable de la conformité de votre utilisation à la loi applicable.' },
      { heading: 'Service bien-être ; aucune relation médicale', body: 'Luna29 fournit des outils de bien-être, de conscience du cycle et de réflexion à des fins uniquement informatives. Son utilisation ne crée aucune relation médecin-patient, thérapeute-client ou relation clinique agréée. Luna29 n\'est pas un dispositif médical et n\'est pas approuvée par la FDA ou tout autre régulateur comme produit diagnostique ou thérapeutique.' },
      { heading: 'Comptes et abonnements Stripe', body: 'Vous êtes responsable de la protection de vos identifiants et de toute activité sous votre compte. Les abonnements payants sont facturés via Stripe, Inc. ; les conditions de paiement, renouvellement et annulation sont soumises au checkout et aux politiques Stripe. Nous pouvons suspendre ou résilier l\'accès en cas de non-paiement, fraude ou violation des présentes conditions.' },
      { heading: 'Utilisation acceptable', body: 'Vous ne devez pas faire un usage abusif de Luna29, tenter un accès non autorisé, extraire ou rétroconcevoir le service sauf autorisation légale, perturber l\'infrastructure, téléverser du contenu illicite ou nuisible, ni utiliser le service pour des soins d\'urgence ou remplacer un jugement professionnel.' },
      { heading: 'Propriété intellectuelle', body: 'Luna29, sa marque, son logiciel et son contenu nous appartiennent ou appartiennent à nos concédants et sont protégés par les lois sur la propriété intellectuelle. Nous vous accordons une licence limitée, non exclusive et non transférable pour un usage personnel non commercial conformément aux présentes conditions.' },
      { heading: 'Exclusions et limitation de responsabilité', body: 'Luna29 est fourni « en l\'état » et « selon disponibilité » sans garantie dans la mesure maximale permise par la loi. Dans la mesure permise, nous ne sommes pas responsables des dommages indirects, accessoires, spéciaux, consécutifs ou punitifs, ni des décisions prises sur la base des sorties de l\'application. Notre responsabilité agrégée ne dépassera pas les montants payés au cours des douze mois précédant la réclamation ou cent dollars U.S.' },
      { heading: 'Indemnisation', body: 'Vous acceptez d\'indemniser et de dégager de toute responsabilité Luna29 et ses opérateurs pour les réclamations résultant de votre mauvaise utilisation, violation des présentes conditions ou atteinte aux droits de tiers, sauf en cas de notre négligence grave ou faute intentionnelle.' },
      { heading: 'Résiliation et modifications', body: 'Nous pouvons suspendre ou résilier votre accès en cas de violation des présentes conditions ou pour protéger le service. Vous pouvez cesser d\'utiliser Luna29 à tout moment. Nous pouvons modifier les fonctionnalités ou les présentes conditions en publiant des versions mises à jour avec une nouvelle date d\'effet. L\'utilisation continue après modification vaut acceptation lorsque la loi le permet.' },
      { heading: 'Droit applicable et litiges', body: 'Les présentes conditions visent à s\'aligner sur les pratiques de services en ligne U.S. Sauf obligation contraire de droit local impératif, les litiges seront résolus conformément au droit U.S. applicable et aux tribunaux compétents. Contactez-nous via la page Contact pour toute question.' },
    ],
  },
  de: {
    title: 'Nutzungsbedingungen',
    subtitle: 'Baseline-Servicebedingungen (U.S.-orientiert) für den Zugang zu Luna29 und verantwortungsvolle Nutzung.',
    sections: [
      { heading: 'Annahme der Bedingungen', body: 'Durch Zugriff auf oder Nutzung von Luna29 stimmen Sie diesen Nutzungsbedingungen und unserem Datenschutzhinweis zu. Wenn Sie nicht zustimmen, nutzen Sie den Dienst nicht. Nutzen Sie Luna29 für eine Organisation, versichern Sie, diese binden zu dürfen.' },
      { heading: 'Teilnahmeberechtigung', body: 'Sie müssen mindestens 18 Jahre alt sein oder das Volljährigkeitsalter in Ihrer Rechtsordnung erreicht haben, um ein Konto zu erstellen oder zu abonnieren. Luna29 richtet sich nicht an Kinder unter 13 Jahren. Sie sind für die Einhaltung anwendbaren Rechts verantwortlich.' },
      { heading: 'Wellness-Dienst; keine medizinische Beziehung', body: 'Luna29 bietet Wellness-, Zyklus-Bewusstseins- und Reflexionstools ausschließlich zu Informationszwecken. Die Nutzung begründet keine Arzt-Patient-, Therapeut-Klient- oder andere klinische Beziehung. Luna29 ist kein Medizinprodukt und nicht von der FDA oder einer Behörde als Diagnose- oder Therapieprodukt zugelassen.' },
      { heading: 'Konten und Stripe-Abonnements', body: 'Sie sind für den Schutz Ihrer Zugangsdaten und alle Aktivitäten unter Ihrem Konto verantwortlich. Kostenpflichtige Mitgliedschaften werden über Stripe, Inc. abgerechnet; Zahlungs-, Verlängerungs- und Kündigungsbedingungen unterliegen Checkout und Stripe-Richtlinien. Wir können den Zugang bei Nichtzahlung, Betrug oder Verstoß sperren oder beenden.' },
      { heading: 'Zulässige Nutzung', body: 'Sie dürfen Luna29 nicht missbrauchen, unbefugten Zugriff versuchen, den Dienst scrapen oder reverse-engineeren, außer gesetzlich erlaubt, die Infrastruktur stören, rechtswidrige oder schädliche Inhalte hochladen oder den Dienst für Notfallversorgung oder Ersatz professioneller Beurteilung nutzen.' },
      { heading: 'Geistiges Eigentum', body: 'Luna29, Marken, Software und Inhalte gehören uns oder Lizenzgebern und sind durch IP-Rechte geschützt. Wir gewähren eine begrenzte, nicht ausschließliche, nicht übertragbare Lizenz für persönliche, nicht kommerzielle Nutzung gemäß diesen Bedingungen.' },
      { heading: 'Haftungsausschluss und Haftungsbeschränkung', body: 'Luna29 wird „wie besehen" und „wie verfügbar" ohne Gewährleistung im gesetzlich zulässigen Umfang bereitgestellt. Soweit zulässig haften wir nicht für indirekte, beiläufige, besondere, Folge- oder Strafschäden oder Entscheidungen auf Basis von App-Ausgaben. Unsere Gesamthaftung übersteigt nicht die in den zwölf Monaten vor der Forderung gezahlten Beträge oder einhundert US-Dollar.' },
      { heading: 'Freistellung', body: 'Sie stellen Luna29 und Betreiber von Ansprüchen frei, die aus Missbrauch, Verstoß gegen diese Bedingungen oder Verletzung Dritterrechte entstehen, außer bei grober Fahrlässigkeit oder vorsätzlichem Fehlverhalten unsererseits.' },
      { heading: 'Beendigung und Änderungen', body: 'Wir können den Zugang bei Verstoß oder zum Schutz des Dienstes jederzeit sperren oder beenden. Sie können Luna29 jederzeit nicht mehr nutzen. Wir können Funktionen oder Bedingungen mit neuem Gültigkeitsdatum aktualisieren. Fortgesetzte Nutzung nach Änderungen gilt als Annahme, soweit gesetzlich zulässig.' },
      { heading: 'Anwendbares Recht und Streitigkeiten', body: 'Diese Bedingungen orientieren sich an U.S.-Online-Service-Praktiken. Sofern zwingendes lokales Recht nichts anderes verlangt, werden Streitigkeiten nach anwendbarem U.S.-Recht und zuständigen Gerichten beigelegt. Fragen über die Contact-Seite.' },
    ],
  },
  zh: {
    title: '使用条款',
    subtitle: '管辖 Luna29 访问与Responsible使用的美国导向基础服务条款。',
    sections: [
      { heading: '条款接受', body: '访问或使用 Luna29 即表示您同意本使用条款及隐私声明。若不同意，请勿使用服务。若代表组织使用，您声明有权使该组织受约束。' },
      { heading: '资格', body: '创建账户或订阅须年满 18 周岁或您所在司法辖区的成年年龄。Luna29 不面向 13 岁以下儿童。您须确保使用符合适用法律。' },
      { heading: 'Wellness 服务；无医疗关系', body: 'Luna29 仅提供 wellness、周期觉察与反思工具，仅供信息参考。使用不构成医患、治疗师-来访者或任何持证临床关系。Luna29 非医疗器械，未经 FDA 或任何监管机构批准为诊断或治疗产品。' },
      { heading: '账户与 Stripe 订阅', body: '您须保护账户凭据并对账户下一切活动负责。付费会员通过 Stripe, Inc. 计费；支付、续订与取消受结账流程及 Stripe 政策约束。我们可能因欠费、欺诈或违反条款暂停或终止访问。' },
      { heading: '可接受使用', body: '不得滥用 Luna29、尝试未授权访问、抓取或逆向工程服务（法律允许除外）、干扰基础设施、上传违法或有害内容，或将服务用于紧急医疗或替代专业判断。' },
      { heading: '知识产权', body: 'Luna29 及其品牌、软件与内容归我们或许可方所有，受知识产权法保护。我们授予您有限、非独占、不可转让的个人非商业使用许可。' },
      { heading: '免责声明与责任限制', body: 'Luna29 按「现状」及「可用性」提供，在法律允许的最大范围内不作任何保证。在法律允许范围内，我们不对间接、附带、特殊、后果性或惩罚性损害，或基于应用输出的决策负责。我们的总责任不超过索赔前十二个月您支付金额或一百美元（以较高者为准）。' },
      { heading: '赔偿', body: '您同意就因滥用服务、违反本条款或侵犯第三方权利引起的索赔，向 Luna29 及其运营方赔偿并使其免责，但因我们重大过失或故意违法行为 导致的除外。' },
      { heading: '终止与变更', body: '我们可能因违反条款或为保护服务随时暂停或终止访问。您可随时停止使用 Luna29。我们可通过发布含新生效日期的更新条款修改功能或条款。法律允许时，变更后继续使用即构成接受。' },
      { heading: '适用法律与争议', body: '本条款旨在符合美国在线服务惯例。除非强制性当地法律另有要求，争议依适用的美国法律及有管辖权的法院解决。有关问题请通过 Contact 页面联系我们。' },
    ],
  },
  ja: {
    title: '利用規約',
    subtitle: 'Luna29 へのアクセスと responsible な利用を規律する米国向けベースラインのサービス条件。',
    sections: [
      { heading: '規約への同意', body: 'Luna29 にアクセスまたは利用することで、本利用規約およびプライバシー通知に同意したものとみなされます。同意しない場合は利用しないでください。組織に代わって利用する場合、当該組織を拘束する権限があることを表明します。' },
      { heading: '利用資格', body: 'アカウント作成またはサブスクリプションには、18 歳以上、またはお住まいの法域の成年年齢が必要です。Luna29 は 13 歳未満の児童を対象としていません。適用法への遵守はお客様の責任です。' },
      { heading: 'ウェルネスサービス；医療関係の不成立', body: 'Luna29 は情報提供目的のみのウェルネス、サイクル認識、内省ツールを提供します。利用により医師-患者、セラピスト-クライアント、その他の臨床提供者関係は成立しません。Luna29 は医療機器ではなく、FDA または規制当局による診断・治療製品としての承認を受けていません。' },
      { heading: 'アカウントと Stripe サブスクリプション', body: 'アカウント資格情報の保護およびアカウント下のすべての活動はお客様の責任です。有料メンバーシップは Stripe, Inc. を通じて請求されます。支払い、更新、解約条件はチェックアウトおよび Stripe ポリシーに従います。未払い、不正、規約違反の場合、アクセスを停止または終了する場合があります。' },
      { heading: '許容される利用', body: 'Luna29 の misuse、不正アクセスの試み、法令で許される場合を除くスクレイピングまたはリバースエンジニアリング、インフラへの妨害、違法または有害コンテンツのアップロード、緊急医療または専門的判断の代替としての利用をしてはなりません。' },
      { heading: '知的財産', body: 'Luna29、そのブランド、ソフトウェア、コンテンツは当社またはライセンサーに帰属し、知的財産法で保護されています。本規約に従い、個人的非商用目的の限定的、非独占的、譲渡不能な利用ライセンスを付与します。' },
      { heading: '免責および責任制限', body: 'Luna29 は法令で許される最大限において、いかなる保証もなく「現状有姿」および「提供可能な限り」で提供されます。間接、付随、特別、結果的または懲罰的損害、またはアプリ出力に基づく判断について、法令で許される範囲で責任を負いません。当社の総責任額は、請求前 12 か月間の支払額または 100 米ドルのいずれか大きい方を超えません。' },
      { heading: '補償', body: 'サービスの misuse、本規約違反、第三者権利侵害に起因する請求について、当社の重大な過失または故意的不法行為を除き、Luna29 および運営者を補償し免責することに同意します。' },
      { heading: '終了と変更', body: '規約違反またはサービス保護のため、いつでもアクセスを停止または終了できます。お客様はいつでも利用を中止できます。新たな発効日付きの更新規約を掲載して機能または規約を変更する場合があります。法令で許される場合、変更後の継続利用は同意とみなされます。' },
      { heading: '準拠法と紛争', body: '本規約は米国オンラインサービスの慣行に沿うことを意図しています。強行的な現地法が別段要求しない限り、紛争は適用される米国法および管轄裁判所に従い解決されます。質問は Contact ページからお問い合わせください。' },
    ],
  },
  pt: {
    title: 'Termos de uso',
    subtitle: 'Termos base do serviço (orientados aos EUA) que regem o acesso à Luna29 e o uso responsável.',
    sections: [
      { heading: 'Aceitação dos termos', body: 'Ao acessar ou usar a Luna29, você concorda com estes Termos de uso e nosso Aviso de privacidade. Se não concordar, não use o serviço. Se usar a Luna29 em nome de uma organização, declara ter autoridade para vinculá-la.' },
      { heading: 'Elegibilidade', body: 'Você deve ter pelo menos 18 anos, ou a maioridade em sua jurisdição, para criar conta ou assinar. A Luna29 não se destina a menores de 13 anos. Você é responsável por garantir conformidade com a lei aplicável.' },
      { heading: 'Serviço de bem-estar; sem relação médica', body: 'A Luna29 oferece ferramentas de bem-estar, consciência do ciclo e reflexão apenas para fins informativos. O uso não cria relação médico-paciente, terapeuta-cliente ou qualquer relação clínica licenciada. A Luna29 não é dispositivo médico nem aprovada pela FDA ou outro regulador como produto diagnóstico ou terapêutico.' },
      { heading: 'Contas e assinaturas Stripe', body: 'Você é responsável por proteger credenciais e por toda atividade em sua conta. Assinaturas pagas são cobradas via Stripe, Inc.; termos de pagamento, renovação e cancelamento estão sujeitos ao checkout e políticas da Stripe. Podemos suspender ou encerrar acesso por inadimplência, fraude ou violação destes termos.' },
      { heading: 'Uso aceitável', body: 'Você não deve fazer uso indevido da Luna29, tentar acesso não autorizado, extrair ou fazer engenharia reversa do serviço salvo permitido por lei, interferir na infraestrutura, enviar conteúdo ilícito ou nocivo, ou usar o serviço para emergência médica ou substituir julgamento profissional.' },
      { heading: 'Propriedade intelectual', body: 'A Luna29, sua marca, software e conteúdo pertencem a nós ou licenciadores e são protegidos por leis de propriedade intelectual. Concedemos licença limitada, não exclusiva e intransferível para uso pessoal não comercial conforme estes termos.' },
      { heading: 'Isenções e limitação de responsabilidade', body: 'A Luna29 é fornecida «no estado em que se encontra» e «conforme disponível» sem garantias na máxima extensão permitida por lei. Na medida permitida, não somos responsáveis por danos indiretos, incidentais, especiais, consequenciais ou punitivos, ou decisões baseadas em saídas do app. Nossa responsabilidade agregada não excederá valores pagos nos doze meses anteriores à reclamação ou cem dólares americanos.' },
      { heading: 'Indenização', body: 'Você concorda em indenizar e isentar a Luna29 e operadores de reclamações decorrentes de uso indevido, violação destes termos ou violação de direitos de terceiros, exceto por nossa negligência grave ou conduta dolosa.' },
      { heading: 'Rescisão e alterações', body: 'Podemos suspender ou encerrar acesso por violação destes termos ou para proteger o serviço. Você pode parar de usar a Luna29 a qualquer momento. Podemos modificar recursos ou estes termos publicando versões atualizadas com nova data de vigência. Uso continuado após alterações constitui aceitação quando permitido por lei.' },
      { heading: 'Lei aplicável e disputas', body: 'Estes termos visam alinhar-se às práticas de serviços online dos EUA. Salvo lei local imperativa em contrário, disputas serão resolvidas conforme lei aplicável dos EUA e tribunais competentes. Contate-nos pela página Contact para dúvidas.' },
    ],
  },
  ar: {
    title: 'شروط الاستخدام',
    subtitle: 'شروط خدمة أساسية (موجهة للسوق الأمريكي) تحكم الوصول إلى Luna29 والاستخدام المسؤول.',
    sections: [
      { heading: 'قبول الشروط', body: 'بالوصول إلى Luna29 أو استخدامها، فإنك توافق على شروط الاستخدام هذه وإشعار الخصوصية. إذا لم توافق، لا تستخدم الخدمة. إذا استخدمت Luna29 نيابة عن منظمة، فأنت تؤكد سلطتك لإلزامها.' },
      { heading: 'الأهلية', body: 'يجب أن يكون عمرك 18 عاماً على الأقل، أو سن الرشد في ولايتك القضائية، لإنشاء حساب أو الاشتراك. Luna29 غير موجهة للأطفال دون 13 عاماً. أنت مسؤول عن امتثال استخدامك للقانون المعمول به.' },
      { heading: 'خدمة العافية؛ لا علاقة طبية', body: 'توفر Luna29 أدوات العافية ووعي الدورة والتأمل لأغراض إعلامية فقط. الاستخدام لا ينشئ علاقة طبيب-مريض أو معالج-مراجع أو أي علاقة سريرية مرخّصة. Luna29 ليست جهازاً طبياً ولم تُعتمد من FDA أو أي جهة تنظيمية كمنتج تشخيصي أو علاجي.' },
      { heading: 'الحسابات واشتراكات Stripe', body: 'أنت مسؤول عن حماية بيانات اعتماد حسابك وعن كل نشاط تحت حسابك. تُعالَج العضويات المدفوعة عبر Stripe, Inc.؛ تخضع شروط الدفع والتجديد والإلغاء لعملية الدفع وسياسات Stripe. قد نعلق أو ننهي الوصول لعدم الدفع أو الاحتيال أو مخالفة هذه الشروط.' },
      { heading: 'الاستخدام المقبول', body: 'يجب ألا تسيء استخدام Luna29 أو تحاول الوصول غير المصرح به أو تستخرج البيانات أو تعكس هندسة الخدمة إلا حيث يسمح القانون، أو تتداخل مع البنية التحتية، أو ترفع محتوى غير قانوني أو ضار، أو تستخدم الخدمة للرعاية الطارئة أو لاستبدال الحكم المهني.' },
      { heading: 'الملكية الفكرية', body: 'Luna29 وعلامتها وبرمجياتها ومحتواها مملوكة لنا أو لمرخصينا ومحمية بقوانين الملكية الفكرية. نمنحك ترخيصاً محدوداً وغير حصري وغير قابل للتحويل للاستخدام الشخصي غير التجاري وفق هذه الشروط.' },
      { heading: 'إخلاء المسؤولية وحدودها', body: 'تُقدَّم Luna29 «كما هي» و«حسب التوفر» دون ضمانات إلى أقصى حد يسمح به القانون. حيث يسمح القانون، لا نتحمل مسؤولية الأضرار غير المباشرة أو العرضية أو الخاصة أو التبعية أو العقابية، أو القرارات المبنية على مخرجات التطبيق. لا تتجاوز مسؤوليتنا الإجمالية المبالغ المدفوعة في الاثني عشر شهراً السابقة للمطالبة أو مائة دولار أمريكي.' },
      { heading: 'التعويض', body: 'توافق على تعويض Luna29 ومشغّليها والدفاع عنهم من المطالبات الناشئة عن إساءة استخدامك أو مخالفة هذه الشروط أو انتهاك حقوق الغير، إلا إذا نتجت عن إهمالنا الجسيم أو سوء سلوكنا المتعمد.' },
      { heading: 'الإنهاء والتغييرات', body: 'قد نعلق أو ننهي وصولك لانتهاك هذه الشروط أو لحماية الخدمة. يمكنك التوقف عن استخدام Luna29 في أي وقت. قد نعدّل الميزات أو هذه الشروط بنشر نسخ محدّثة بتاريخ سريان جديد. الاستمرار بعد التغييرات يُعد قبولاً حيث يسمح القانون.' },
      { heading: 'القانون الحاكم والنزاعات', body: 'تهدف هذه الشروط إلى مواءمة ممارسات الخدمات الأمريكية عبر الإنترنت. ما لم يفرض القانون المحلي الإلزامي خلاف ذلك، تُحل النزاعات وفق القانون الأمريكي المعمول به والمحاكم المختصة. تواصل معنا عبر صفحة Contact للأسئلة.' },
    ],
  },
  he: {
    title: 'תנאי שימוש',
    subtitle: 'תנאי שירות בסיס (מכוונים לשוק האמריקאי) המסדירים גישה ל-Luna29 ושימוש אחראי.',
    sections: [
      { heading: 'קבלת התנאים', body: 'בגישה או שימוש ב-Luna29 אתם מסכימים לתנאי שימוש אלה ולהודעת הפרטיות. אם אינכם מסכימים, אל תשתמשו בשירות. שימוש בשם ארגון מהווה הצהרה שיש לכם סמכות לחייב אותו.' },
      { heading: 'זכאות', body: 'עליכם להיות בני 18 לפחות, או בגיל הבגירות ביurisdiction שלכם, כדי ליצור חשבון או להירשם למנוי. Luna29 אינה מכוונת לילדים מתחת לגיל 13. אתם אחראים לעמידה בחוק החל.' },
      { heading: 'שירות wellness; ללא יחס רפואי', body: 'Luna29 מספקת כלי wellness, מודעות מחזור והתבוננות למטרות מידע בלבד. השימוש אינו יוצר יחס רופא-מטופל, מטפל-מטופל או יחס קlinי מורשה. Luna29 אינה מכשיר רפואי ואינה מאושרת על ידי FDA או רגulator כמוצר אבחון או טיפול.' },
      { heading: 'חשבונות ומנויי Stripe', body: 'אתם אחראים לשמירת פרטי ההתחברות ולכל פעילות תחת החשבון. מנויים בתשלום מחויבים דרך Stripe, Inc.; תנאי תשלום, חידוש וביטול כפופים ל-checkout ולמדיניות Stripe. אנו עשויים להשעות או לסיים גישה בגין אי-תשלום, הונאה או הפרת תנאים.' },
      { heading: 'שימוש מקובל', body: 'אין לעשות שימוש לרעה ב-Luna29, לנסות גישה בלתי מורשית, לגרד או לבצע הנדסה לאחור למעט כפי שהחוק מתיר, להפריע לתשתית, להעלות תוכן בלתי חוקי או מזיק, או להשתמש בשירות לטיפול חירום או להחלפת שיקול דעת מקצועי.' },
      { heading: 'קניין רוחני', body: 'Luna29, המיתוג, התוכנה והתוכן שלה בבעלותנו או מעניקי הרישיון ומוגנים בדיני קניין רוחני. אנו מעניקים רישיון מוגבל, לא בלעדי ולא ניתן להעברה לשימוש אישי לא מסחרי בהתאם לתנאים.' },
      { heading: 'הצהרות והגבלת אחריות', body: 'Luna29 מסופקת «כפי שהיא» ו«כפי שזמינה» ללא אחריות במידה המרבית שהחוק מתיר. במידה המותרת, לא נהיה אחראים לנזקים עקיפים, ת incidental, מיוחדים, תוצאתיים או עונשיים, או להחלטות המבוססות על פלטי האפליקציה. אחריותנו המצטברת לא תעלה על הסכומים ששילמתם בשנים-עשר החודשים שלפני התביעה או מאה דולר אמריקאי.' },
      { heading: 'שיפוי', body: 'אתם מסכימים לשפות ולפטור את Luna29 ומפעיליה מתביעות הנובעות משימוש לרעה, הפרת תנאים או הפרת זכויות צד שלישי, למעט במקרה של רשלנות חמורה או מכוון מצדנו.' },
      { heading: 'סיום ושינויים', body: 'אנו עשויים להשעות או לסיים גישה בגין הפרת תנאים או להגנה על השירות. ניתן להפסיק שימוש ב-Luna29 בכל עת. אנו עשויים לשנות תכונות או תנאים בפרסום גרסה מעודכנת עם תאריך תחילת תוקף חדש. המשך שימוש לאחר שינויים מהווה קבלה ככל שהחוק מתיר.' },
      { heading: 'דין חל וסכסוכים', body: 'תנאים אלה נועדו להתיישר עם נהגי שירות מקוון בארה"ב. אלא אם דין מקומי מחייב אחרת, סכסוכים ייפתרו לפי דין ארה"ב החל ובבתי משפט מוסמכים. שאלות דרך דף Contact.' },
    ],
  },
};
