import { LangCopy } from '../../constants';

export type LegalUiCopy = {
  back: string;
  modePublic: string;
  modeMember: string;
  effectiveDate: string;
  lastUpdated: string;
  actionsTitle: string;
  actionsBody: string;
  exportData: string;
  deleteHealth: string;
  deleteAll: string;
  legalNotice: string;
  legalNoticeBody: string;
  controllingLanguageNote: string;
  documentsTitle: string;
  feedbackServerExport: string;
  feedbackLocalExport: string;
  feedbackServerSupportDelete: string;
  feedbackLocalHealthDelete: string;
  confirmDeleteAll: string;
  feedbackServerAccountDelete: string;
  feedbackAllLocalDelete: string;
};

export const LEGAL_UI: LangCopy<LegalUiCopy> = {
  en: {
    back: 'Back',
    modePublic: 'PUBLIC LEGAL',
    modeMember: 'MEMBER LEGAL',
    effectiveDate: 'Effective Date',
    lastUpdated: 'Last Updated',
    actionsTitle: 'Self-Service Data Actions',
    actionsBody: 'This device currently uses local storage. You can export or remove local Luna29 data now.',
    exportData: 'Export My Local Data',
    deleteHealth: 'Delete Local Health Data',
    deleteAll: 'Delete All Local Data',
    legalNotice: 'Legal Notice',
    legalNoticeBody: 'This content is a baseline compliance template for U.S.-oriented product disclosures and does not constitute legal advice.',
    controllingLanguageNote: 'English is the controlling language for legal interpretation unless local law requires otherwise. Translations are provided for convenience.',
    documentsTitle: 'Policy documents',
    feedbackServerExport: 'Server export downloaded.',
    feedbackLocalExport: 'Local data export downloaded.',
    feedbackServerSupportDelete: 'Server support data deletion request completed.',
    feedbackLocalHealthDelete: 'Local health data removed',
    confirmDeleteAll: 'Delete all local Luna29 data on this device? This cannot be undone.',
    feedbackServerAccountDelete: 'Server account deletion request completed.',
    feedbackAllLocalDelete: 'All local data removed',
  },
  ru: {
    back: 'Назад',
    modePublic: 'ПУБЛИЧНОЕ ПРАВО',
    modeMember: 'ПРАВО УЧАСТНИКА',
    effectiveDate: 'Дата вступления',
    lastUpdated: 'Последнее обновление',
    actionsTitle: 'Самостоятельные действия с данными',
    actionsBody: 'На этом устройстве используются локальные данные. Вы можете экспортировать или удалить локальные данные Luna29.',
    exportData: 'Экспорт локальных данных',
    deleteHealth: 'Удалить локальные данные здоровья',
    deleteAll: 'Удалить все локальные данные',
    legalNotice: 'Юридическое уведомление',
    legalNoticeBody: 'Этот текст является базовым шаблоном соответствия требованиям для США и не является юридической консультацией.',
    controllingLanguageNote: 'Английская версия является приоритетной для юридической трактовки, если иное не требуется местным законом. Переводы предоставлены для удобства.',
    documentsTitle: 'Документы',
    feedbackServerExport: 'Выгрузка с сервера скачана.',
    feedbackLocalExport: 'Локальная выгрузка данных скачана.',
    feedbackServerSupportDelete: 'Запрос на удаление support-данных на сервере выполнен.',
    feedbackLocalHealthDelete: 'Локальные данные здоровья удалены',
    confirmDeleteAll: 'Удалить все локальные данные Luna29 на этом устройстве? Это действие нельзя отменить.',
    feedbackServerAccountDelete: 'Запрос на удаление аккаунта на сервере выполнен.',
    feedbackAllLocalDelete: 'Все локальные данные удалены',
  },
  uk: {
    back: 'Назад',
    modePublic: 'ПУБЛІЧНІ ПРАВИЛА',
    modeMember: 'ПРАВИЛА УЧАСНИКА',
    effectiveDate: 'Дата набуття чинності',
    lastUpdated: 'Останнє оновлення',
    actionsTitle: 'Самостійні дії з даними',
    actionsBody: 'На цьому пристрої використовується локальне сховище. Ви можете експортувати або видалити локальні дані Luna29.',
    exportData: 'Експортувати мої локальні дані',
    deleteHealth: 'Видалити локальні дані здоровʼя',
    deleteAll: 'Видалити всі локальні дані',
    legalNotice: 'Юридичне повідомлення',
    legalNoticeBody: 'Цей контент є базовим шаблоном комплаєнсу для орієнтованих на США розкриттів і не є юридичною порадою.',
    controllingLanguageNote: 'Англійська версія є пріоритетною для юридичної трактовки, якщо інше не вимагає місцеве право. Переклади надано для зручності.',
    documentsTitle: 'Документи',
    feedbackServerExport: 'Серверний експорт завантажено.',
    feedbackLocalExport: 'Локальний експорт даних завантажено.',
    feedbackServerSupportDelete: 'Запит на видалення support-даних на сервері виконано.',
    feedbackLocalHealthDelete: 'Локальні дані здоровʼя видалено',
    confirmDeleteAll: 'Видалити всі локальні дані Luna29 на цьому пристрої? Це неможливо скасувати.',
    feedbackServerAccountDelete: 'Запит на видалення акаунта на сервері виконано.',
    feedbackAllLocalDelete: 'Усі локальні дані видалено',
  },
  es: {
    back: 'Volver',
    modePublic: 'LEGAL PÚBLICO',
    modeMember: 'LEGAL DE MIEMBRO',
    effectiveDate: 'Fecha de vigencia',
    lastUpdated: 'Última actualización',
    actionsTitle: 'Acciones de datos de autoservicio',
    actionsBody: 'Este dispositivo usa almacenamiento local. Puedes exportar o eliminar ahora los datos locales de Luna29.',
    exportData: 'Exportar mis datos locales',
    deleteHealth: 'Eliminar datos locales de salud',
    deleteAll: 'Eliminar todos los datos locales',
    legalNotice: 'Aviso legal',
    legalNoticeBody: 'Este contenido es una plantilla base de cumplimiento para divulgaciones orientadas a EE. UU. y no constituye asesoría legal.',
    controllingLanguageNote: 'El inglés es el idioma de referencia legal salvo que la ley local exija lo contrario. Las traducciones se ofrecen por conveniencia.',
    documentsTitle: 'Documentos',
    feedbackServerExport: 'Exportación del servidor descargada.',
    feedbackLocalExport: 'Exportación local de datos descargada.',
    feedbackServerSupportDelete: 'Solicitud de eliminación de datos de soporte en servidor completada.',
    feedbackLocalHealthDelete: 'Datos locales de salud eliminados',
    confirmDeleteAll: '¿Eliminar todos los datos locales de Luna29 en este dispositivo? Esta acción no se puede deshacer.',
    feedbackServerAccountDelete: 'Solicitud de eliminación de cuenta en servidor completada.',
    feedbackAllLocalDelete: 'Todos los datos locales eliminados',
  },
  fr: {
    back: 'Retour',
    modePublic: 'JURIDIQUE PUBLIC',
    modeMember: 'JURIDIQUE MEMBRE',
    effectiveDate: 'Date d’effet',
    lastUpdated: 'Dernière mise à jour',
    actionsTitle: 'Actions de données en libre-service',
    actionsBody: 'Cet appareil utilise un stockage local. Vous pouvez exporter ou supprimer les données locales Luna29.',
    exportData: 'Exporter mes données locales',
    deleteHealth: 'Supprimer les données santé locales',
    deleteAll: 'Supprimer toutes les données locales',
    legalNotice: 'Mentions légales',
    legalNoticeBody: 'Ce contenu est un modèle de conformité de base pour des divulgations orientées U.S. et ne constitue pas un conseil juridique.',
    controllingLanguageNote: 'L’anglais est la langue de référence juridique sauf exigence contraire de la loi locale. Les traductions sont fournies à titre de commodité.',
    documentsTitle: 'Documents',
    feedbackServerExport: 'Export serveur téléchargé.',
    feedbackLocalExport: 'Export local des données téléchargé.',
    feedbackServerSupportDelete: 'Demande de suppression des données support sur serveur effectuée.',
    feedbackLocalHealthDelete: 'Données santé locales supprimées',
    confirmDeleteAll: 'Supprimer toutes les données locales Luna29 sur cet appareil ? Cette action est irréversible.',
    feedbackServerAccountDelete: 'Demande de suppression du compte sur serveur effectuée.',
    feedbackAllLocalDelete: 'Toutes les données locales supprimées',
  },
  de: {
    back: 'Zurück',
    modePublic: 'ÖFFENTLICH RECHTLICH',
    modeMember: 'MITGLIED RECHTLICH',
    effectiveDate: 'Gültig ab',
    lastUpdated: 'Zuletzt aktualisiert',
    actionsTitle: 'Self-Service-Datenaktionen',
    actionsBody: 'Dieses Gerät nutzt lokalen Speicher. Sie können lokale Luna29-Daten jetzt exportieren oder entfernen.',
    exportData: 'Meine lokalen Daten exportieren',
    deleteHealth: 'Lokale Gesundheitsdaten löschen',
    deleteAll: 'Alle lokalen Daten löschen',
    legalNotice: 'Rechtlicher Hinweis',
    legalNoticeBody: 'Dieser Inhalt ist eine Basis-Compliance-Vorlage für U.S.-orientierte Offenlegungen und stellt keine Rechtsberatung dar.',
    controllingLanguageNote: 'Englisch ist die maßgebliche Sprache für die rechtliche Auslegung, sofern lokales Recht nichts anderes verlangt. Übersetzungen dienen der Verständlichkeit.',
    documentsTitle: 'Dokumente',
    feedbackServerExport: 'Server-Export heruntergeladen.',
    feedbackLocalExport: 'Lokaler Datenexport heruntergeladen.',
    feedbackServerSupportDelete: 'Anfrage zur Löschung von Support-Daten auf dem Server abgeschlossen.',
    feedbackLocalHealthDelete: 'Lokale Gesundheitsdaten gelöscht',
    confirmDeleteAll: 'Alle lokalen Luna29-Daten auf diesem Gerät löschen? Dies kann nicht rückgängig gemacht werden.',
    feedbackServerAccountDelete: 'Anfrage zur Kontolöschung auf dem Server abgeschlossen.',
    feedbackAllLocalDelete: 'Alle lokalen Daten gelöscht',
  },
  zh: {
    back: '返回',
    modePublic: '公开法律',
    modeMember: '会员法律',
    effectiveDate: '生效日期',
    lastUpdated: '最后更新',
    actionsTitle: '自助数据操作',
    actionsBody: '此设备当前使用本地存储。你可以立即导出或删除 Luna29 本地数据。',
    exportData: '导出我的本地数据',
    deleteHealth: '删除本地健康数据',
    deleteAll: '删除所有本地数据',
    legalNotice: '法律声明',
    legalNoticeBody: '本内容为面向美国披露要求的基础合规模板，不构成法律建议。',
    controllingLanguageNote: '除非当地法律另有要求，英文版本为法律解释之优先文本。译文仅供参考。',
    documentsTitle: '政策文件',
    feedbackServerExport: '服务器导出已下载。',
    feedbackLocalExport: '本地数据导出已下载。',
    feedbackServerSupportDelete: '服务器支持数据删除请求已完成。',
    feedbackLocalHealthDelete: '本地健康数据已删除',
    confirmDeleteAll: '删除此设备上的所有 Luna29 本地数据？此操作无法撤销。',
    feedbackServerAccountDelete: '服务器账户删除请求已完成。',
    feedbackAllLocalDelete: '所有本地数据已删除',
  },
  ja: {
    back: '戻る',
    modePublic: '公開リーガル',
    modeMember: 'メンバーリーガル',
    effectiveDate: '発効日',
    lastUpdated: '最終更新',
    actionsTitle: 'セルフサービスデータ操作',
    actionsBody: 'このデバイスはローカルストレージを使用しています。Luna29のローカルデータをエクスポートまたは削除できます。',
    exportData: 'ローカルデータをエクスポート',
    deleteHealth: 'ローカル健康データを削除',
    deleteAll: 'すべてのローカルデータを削除',
    legalNotice: '法的通知',
    legalNoticeBody: 'この内容は米国向け開示のための基本的なコンプライアンステンプレートであり、法的助言ではありません。',
    controllingLanguageNote: '現地法で別段の定めがない限り、英語版が法的解釈の優先文書です。翻訳は便宜上提供されます。',
    documentsTitle: 'ポリシー文書',
    feedbackServerExport: 'サーバーエクスポートをダウンロードしました。',
    feedbackLocalExport: 'ローカルデータエクスポートをダウンロードしました。',
    feedbackServerSupportDelete: 'サーバー上のサポートデータ削除リクエストが完了しました。',
    feedbackLocalHealthDelete: 'ローカル健康データを削除しました',
    confirmDeleteAll: 'このデバイス上のLuna29ローカルデータをすべて削除しますか？元に戻せません。',
    feedbackServerAccountDelete: 'サーバー上のアカウント削除リクエストが完了しました。',
    feedbackAllLocalDelete: 'すべてのローカルデータを削除しました',
  },
  pt: {
    back: 'Voltar',
    modePublic: 'LEGAL PÚBLICO',
    modeMember: 'LEGAL DE MEMBRO',
    effectiveDate: 'Data de vigência',
    lastUpdated: 'Última atualização',
    actionsTitle: 'Ações de dados em autoatendimento',
    actionsBody: 'Este dispositivo usa armazenamento local. Você pode exportar ou remover agora os dados locais da Luna29.',
    exportData: 'Exportar meus dados locais',
    deleteHealth: 'Excluir dados locais de saúde',
    deleteAll: 'Excluir todos os dados locais',
    legalNotice: 'Aviso legal',
    legalNoticeBody: 'Este conteúdo é um modelo básico de conformidade para divulgações orientadas aos EUA e não constitui aconselhamento jurídico.',
    controllingLanguageNote: 'O inglês é o idioma de referência legal, salvo exigência em contrário da lei local. As traduções são fornecidas por conveniência.',
    documentsTitle: 'Documentos',
    feedbackServerExport: 'Exportação do servidor baixada.',
    feedbackLocalExport: 'Exportação local de dados baixada.',
    feedbackServerSupportDelete: 'Solicitação de exclusão de dados de suporte no servidor concluída.',
    feedbackLocalHealthDelete: 'Dados locais de saúde removidos',
    confirmDeleteAll: 'Excluir todos os dados locais da Luna29 neste dispositivo? Esta ação não pode ser desfeita.',
    feedbackServerAccountDelete: 'Solicitação de exclusão de conta no servidor concluída.',
    feedbackAllLocalDelete: 'Todos os dados locais removidos',
  },
  ar: {
    back: 'رجوع',
    modePublic: 'قانوني عام',
    modeMember: 'قانوني للعضو',
    effectiveDate: 'تاريخ السريان',
    lastUpdated: 'آخر تحديث',
    actionsTitle: 'إجراءات البيانات الذاتية',
    actionsBody: 'يستخدم هذا الجهاز حالياً التخزين المحلي. يمكنك تصدير أو إزالة بيانات Luna29 المحلية الآن.',
    exportData: 'تصدير بياناتي المحلية',
    deleteHealth: 'حذف بيانات الصحة المحلية',
    deleteAll: 'حذف كل البيانات المحلية',
    legalNotice: 'إشعار قانوني',
    legalNoticeBody: 'هذا المحتوى قالب امتثال أساسي للإفصاحات الموجّهة للسوق الأمريكي ولا يُعدّ استشارة قانونية.',
    controllingLanguageNote: 'الإنجليزية هي اللغة المرجعية للتفسير القانوني ما لم يقتضِ القانون المحلي خلاف ذلك. الترجمات مقدّمة للتسهيل.',
    documentsTitle: 'المستندات',
    feedbackServerExport: 'تم تنزيل التصدير من الخادم.',
    feedbackLocalExport: 'تم تنزيل التصدير المحلي.',
    feedbackServerSupportDelete: 'اكتمل طلب حذف بيانات الدعم على الخادم.',
    feedbackLocalHealthDelete: 'تمت إزالة بيانات الصحة المحلية',
    confirmDeleteAll: 'حذف كل بيانات Luna29 المحلية على هذا الجهاز؟ لا يمكن التراجع عن ذلك.',
    feedbackServerAccountDelete: 'اكتمل طلب حذف الحساب على الخادم.',
    feedbackAllLocalDelete: 'تمت إزالة كل البيانات المحلية',
  },
  he: {
    back: 'חזרה',
    modePublic: 'משפטי ציבורי',
    modeMember: 'משפטי חברה',
    effectiveDate: 'תאריך תחילת תוקף',
    lastUpdated: 'עודכן לאחרונה',
    actionsTitle: 'פעולות נתונים בשירות עצמי',
    actionsBody: 'המכשיר הזה משתמש כרגע באחסון מקומי. אפשר לייצא או להסיר נתוני Luna29 מקומיים עכשיו.',
    exportData: 'ייצוא הנתונים המקומיים שלי',
    deleteHealth: 'מחיקת נתוני בריאות מקומיים',
    deleteAll: 'מחיקת כל הנתונים המקומיים',
    legalNotice: 'הודעה משפטית',
    legalNoticeBody: 'התוכן הזה הוא תבנית ציות בסיסית לגילויים מוצריים מכוונים לשוק האמריקאי ואינו ייעוץ משפטי.',
    controllingLanguageNote: 'אנגלית היא שפת הייחוס המשפטית אלא אם החוק המקומי דורש אחרת. תרגומים מסופקים לנוחות.',
    documentsTitle: 'מסמכי מדיניות',
    feedbackServerExport: 'ייצוא מהשרת הורד.',
    feedbackLocalExport: 'ייצוא נתונים מקומי הורד.',
    feedbackServerSupportDelete: 'בקשת מחיקת נתוני תמיכה בשרת הושלמה.',
    feedbackLocalHealthDelete: 'נתוני בריאות מקומיים הוסרו',
    confirmDeleteAll: 'למחוק את כל נתוני Luna29 המקומיים במכשיר הזה? לא ניתן לבטל.',
    feedbackServerAccountDelete: 'בקשת מחיקת חשבון בשרת הושלמה.',
    feedbackAllLocalDelete: 'כל הנתונים המקומיים הוסרו',
  },
};
